
// This file has been generated by the GUI designer. Do not modify.
namespace DeMixer
{
	public partial class SaveProfileDialog
	{
		private global::Gtk.VBox vbox4;
		private global::Gtk.Entry ProfileNameEdit;
		private global::Gtk.HBox hbox4;
		private global::Gtk.CheckButton SaveSourceCb;
		private global::Gtk.CheckButton SaveCompositionCb;
		private global::Gtk.CheckButton SaveEffectsCb;
		private global::Gtk.Button buttonCancel;
		private global::Gtk.Button buttonOk;
		
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget DeMixer.SaveProfileDialog
			this.Name = "DeMixer.SaveProfileDialog";
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			this.Modal = true;
			this.BorderWidth = ((uint)(3));
			// Internal child DeMixer.SaveProfileDialog.VBox
			global::Gtk.VBox w1 = this.VBox;
			w1.Name = "dialog1_VBox";
			w1.BorderWidth = ((uint)(2));
			// Container child dialog1_VBox.Gtk.Box+BoxChild
			this.vbox4 = new global::Gtk.VBox ();
			this.vbox4.Name = "vbox4";
			this.vbox4.Spacing = 6;
			// Container child vbox4.Gtk.Box+BoxChild
			this.ProfileNameEdit = new global::Gtk.Entry ();
			this.ProfileNameEdit.CanFocus = true;
			this.ProfileNameEdit.Name = "ProfileNameEdit";
			this.ProfileNameEdit.IsEditable = true;
			this.ProfileNameEdit.InvisibleChar = '●';
			this.vbox4.Add (this.ProfileNameEdit);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.ProfileNameEdit]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			// Container child vbox4.Gtk.Box+BoxChild
			this.hbox4 = new global::Gtk.HBox ();
			this.hbox4.Name = "hbox4";
			this.hbox4.Spacing = 6;
			this.hbox4.BorderWidth = ((uint)(3));
			// Container child hbox4.Gtk.Box+BoxChild
			this.SaveSourceCb = new global::Gtk.CheckButton ();
			this.SaveSourceCb.CanFocus = true;
			this.SaveSourceCb.Name = "SaveSourceCb";
			this.SaveSourceCb.Label = global::Mono.Unix.Catalog.GetString ("Save source");
			this.SaveSourceCb.DrawIndicator = true;
			this.SaveSourceCb.UseUnderline = true;
			this.hbox4.Add (this.SaveSourceCb);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.SaveSourceCb]));
			w3.Position = 0;
			// Container child hbox4.Gtk.Box+BoxChild
			this.SaveCompositionCb = new global::Gtk.CheckButton ();
			this.SaveCompositionCb.CanFocus = true;
			this.SaveCompositionCb.Name = "SaveCompositionCb";
			this.SaveCompositionCb.Label = global::Mono.Unix.Catalog.GetString ("Save composition");
			this.SaveCompositionCb.DrawIndicator = true;
			this.SaveCompositionCb.UseUnderline = true;
			this.hbox4.Add (this.SaveCompositionCb);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.SaveCompositionCb]));
			w4.Position = 1;
			// Container child hbox4.Gtk.Box+BoxChild
			this.SaveEffectsCb = new global::Gtk.CheckButton ();
			this.SaveEffectsCb.CanFocus = true;
			this.SaveEffectsCb.Name = "SaveEffectsCb";
			this.SaveEffectsCb.Label = global::Mono.Unix.Catalog.GetString ("Save effects");
			this.SaveEffectsCb.DrawIndicator = true;
			this.SaveEffectsCb.UseUnderline = true;
			this.hbox4.Add (this.SaveEffectsCb);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.SaveEffectsCb]));
			w5.Position = 2;
			this.vbox4.Add (this.hbox4);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.hbox4]));
			w6.Position = 1;
			w6.Expand = false;
			w6.Fill = false;
			w1.Add (this.vbox4);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(w1 [this.vbox4]));
			w7.Position = 0;
			w7.Expand = false;
			w7.Fill = false;
			// Internal child DeMixer.SaveProfileDialog.ActionArea
			global::Gtk.HButtonBox w8 = this.ActionArea;
			w8.Name = "dialog1_ActionArea";
			w8.Spacing = 6;
			w8.BorderWidth = ((uint)(5));
			w8.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(4));
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.buttonCancel = new global::Gtk.Button ();
			this.buttonCancel.CanDefault = true;
			this.buttonCancel.CanFocus = true;
			this.buttonCancel.Name = "buttonCancel";
			this.buttonCancel.UseStock = true;
			this.buttonCancel.UseUnderline = true;
			this.buttonCancel.Label = "gtk-cancel";
			this.AddActionWidget (this.buttonCancel, -6);
			global::Gtk.ButtonBox.ButtonBoxChild w9 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w8 [this.buttonCancel]));
			w9.Expand = false;
			w9.Fill = false;
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.buttonOk = new global::Gtk.Button ();
			this.buttonOk.CanDefault = true;
			this.buttonOk.CanFocus = true;
			this.buttonOk.Name = "buttonOk";
			this.buttonOk.UseStock = true;
			this.buttonOk.UseUnderline = true;
			this.buttonOk.Label = "gtk-ok";
			this.AddActionWidget (this.buttonOk, -5);
			global::Gtk.ButtonBox.ButtonBoxChild w10 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w8 [this.buttonOk]));
			w10.Position = 1;
			w10.Expand = false;
			w10.Fill = false;
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 325;
			this.DefaultHeight = 143;
			this.Show ();
		}
	}
}
