
// This file has been generated by the GUI designer. Do not modify.
namespace DeMixer
{
	public partial class ConfigDlg
	{
		private global::Gtk.VBox vbox2;
		private global::Gtk.Notebook notebook1;
		private global::Gtk.VBox SourceVBox;
		private global::Gtk.HBox hbox8;
		private global::Gtk.VBox vbox3;
		private global::Gtk.ComboBox SourceCb;
		private global::Gtk.Label SourceInformationLabel;
		private global::Gtk.Frame frame4;
		private global::Gtk.Alignment SourceSettingsPlace;
		private global::Gtk.Label GtkLabel17;
		private global::Gtk.Label label1;
		private global::Gtk.VBox VBoxcom;
		private global::Gtk.HBox hbox9;
		private global::Gtk.VBox vbox4;
		private global::Gtk.ComboBox CompositionComboBox;
		private global::Gtk.Label CompositionInformationLabel;
		private global::Gtk.HBox CompositionVBox1;
		private global::Gtk.Frame CompositionSettingsFrame;
		private global::Gtk.Alignment CompositionSettingsPlace;
		private global::Gtk.Label GtkLabel16;
		private global::Gtk.Frame frame2;
		private global::Gtk.Alignment GtkAlignment11;
		private global::Gtk.Image imagePreview;
		private global::Gtk.Label GtkLabel18;
		private global::Gtk.Label label3;
		private global::Gtk.VBox vbox5;
		private global::Gtk.HBox hbox2;
		private global::Gtk.VBox vbox7;
		private global::Gtk.HBox hbox10;
		private global::Gtk.ComboBox EffectsComboBox;
		private global::Gtk.Button effectAddBtn;
		private global::Gtk.Label EffectInformationLabel;
		private global::Gtk.HBox hbox3;
		private global::Gtk.ScrolledWindow GtkScrolledWindow;
		private global::Gtk.TreeView EffectsList;
		private global::Gtk.VButtonBox vbuttonbox1;
		private global::Gtk.Button editEffectBtn;
		private global::Gtk.Button upEffectBtn;
		private global::Gtk.Button downEffectBtn;
		private global::Gtk.Button cloneEffectBtn;
		private global::Gtk.Button deleteEffectBtn;
		private global::Gtk.Label label5;
		private global::Gtk.VBox vbox6;
		private global::Gtk.Frame frame3;
		private global::Gtk.Alignment GtkAlignment12;
		private global::Gtk.HBox hbox5;
		private global::Gtk.Label label9;
		private global::Gtk.VBox vbox8;
		private global::Gtk.Label IntervalLabel;
		private global::Gtk.HScale intervalScale;
		private global::Gtk.Label label11;
		private global::Gtk.ComboBox UpdateIntervalModeCb;
		private global::Gtk.Label GtkLabel15;
		private global::Gtk.Frame frame5;
		private global::Gtk.Alignment GtkAlignment13;
		private global::Gtk.VBox vbox9;
		private global::Gtk.HBox hbox4;
		private global::Gtk.CheckButton saveHistoryChBox;
		private global::Gtk.FileChooserButton selectSaveHostoryFolderBox;
		private global::Gtk.CheckButton historyLimitSizeChBox;
		private global::Gtk.SpinButton historyMaxSizeSpin;
		private global::Gtk.Label label8;
		private global::Gtk.HBox hbox6;
		private global::Gtk.CheckButton saveTempImagesCb;
		private global::Gtk.Label GtkLabel20;
		private global::Gtk.Frame frame6;
		private global::Gtk.Alignment GtkAlignment14;
		private global::Gtk.VBox vbox10;
		private global::Gtk.HBox hbox7;
		private global::Gtk.Label label12;
		private global::Gtk.ComboBox languageCB;
		private global::Gtk.CheckButton checkbutton3;
		private global::Gtk.Label GtkLabel21;
		private global::Gtk.Frame frame7;
		private global::Gtk.Alignment GtkAlignment15;
		private global::Gtk.Table table1;
		private global::Gtk.Label label2;
		private global::Gtk.Label label4;
		private global::Gtk.Label label6;
		private global::Gtk.ComboBox scriptAfterCB;
		private global::Gtk.ComboBox scriptBeforeCB;
		private global::Gtk.ComboBox scriptChangeCB;
		private global::Gtk.Label GtkLabel22;
		private global::Gtk.Label label7;
		private global::Gtk.HSeparator hseparator2;
		private global::Gtk.Frame frame1;
		private global::Gtk.Alignment GtkAlignment6;
		private global::Gtk.HBox hbox1;
		private global::Gtk.ComboBox ProfilesCb;
		private global::Gtk.HButtonBox hbuttonbox2;
		private global::Gtk.Button applyProfileBtn;
		private global::Gtk.Button saveProfileBtn;
		private global::Gtk.Button deleteProfileBtn;
		private global::Gtk.Label GtkLabel14;
		private global::Gtk.Button buttonOk;
		
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget DeMixer.ConfigDlg
			this.Name = "DeMixer.ConfigDlg";
			this.Title = global::Mono.Unix.Catalog.GetString ("Demixer config dialog");
			this.WindowPosition = ((global::Gtk.WindowPosition)(1));
			this.Modal = true;
			this.BorderWidth = ((uint)(6));
			// Internal child DeMixer.ConfigDlg.VBox
			global::Gtk.VBox w1 = this.VBox;
			w1.Name = "dialog1_VBox";
			w1.BorderWidth = ((uint)(2));
			// Container child dialog1_VBox.Gtk.Box+BoxChild
			this.vbox2 = new global::Gtk.VBox ();
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 6;
			// Container child vbox2.Gtk.Box+BoxChild
			this.notebook1 = new global::Gtk.Notebook ();
			this.notebook1.CanFocus = true;
			this.notebook1.Name = "notebook1";
			this.notebook1.CurrentPage = 3;
			// Container child notebook1.Gtk.Notebook+NotebookChild
			this.SourceVBox = new global::Gtk.VBox ();
			this.SourceVBox.Name = "SourceVBox";
			this.SourceVBox.Spacing = 6;
			this.SourceVBox.BorderWidth = ((uint)(3));
			// Container child SourceVBox.Gtk.Box+BoxChild
			this.hbox8 = new global::Gtk.HBox ();
			this.hbox8.Name = "hbox8";
			this.hbox8.Spacing = 6;
			// Container child hbox8.Gtk.Box+BoxChild
			this.vbox3 = new global::Gtk.VBox ();
			this.vbox3.Name = "vbox3";
			this.vbox3.Spacing = 6;
			// Container child vbox3.Gtk.Box+BoxChild
			this.SourceCb = global::Gtk.ComboBox.NewText ();
			this.SourceCb.CanFocus = true;
			this.SourceCb.Name = "SourceCb";
			this.vbox3.Add (this.SourceCb);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.SourceCb]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			this.hbox8.Add (this.vbox3);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox8 [this.vbox3]));
			w3.Position = 0;
			w3.Expand = false;
			w3.Fill = false;
			// Container child hbox8.Gtk.Box+BoxChild
			this.SourceInformationLabel = new global::Gtk.Label ();
			this.SourceInformationLabel.Name = "SourceInformationLabel";
			this.SourceInformationLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("SourceInformationLabel");
			this.SourceInformationLabel.UseMarkup = true;
			this.SourceInformationLabel.Wrap = true;
			this.SourceInformationLabel.Selectable = true;
			this.hbox8.Add (this.SourceInformationLabel);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox8 [this.SourceInformationLabel]));
			w4.Position = 1;
			this.SourceVBox.Add (this.hbox8);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.SourceVBox [this.hbox8]));
			w5.Position = 0;
			w5.Expand = false;
			w5.Fill = false;
			// Container child SourceVBox.Gtk.Box+BoxChild
			this.frame4 = new global::Gtk.Frame ();
			this.frame4.Name = "frame4";
			this.frame4.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child frame4.Gtk.Container+ContainerChild
			this.SourceSettingsPlace = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.SourceSettingsPlace.Name = "SourceSettingsPlace";
			this.SourceSettingsPlace.LeftPadding = ((uint)(12));
			this.frame4.Add (this.SourceSettingsPlace);
			this.GtkLabel17 = new global::Gtk.Label ();
			this.GtkLabel17.Name = "GtkLabel17";
			this.GtkLabel17.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Settings</b>");
			this.GtkLabel17.UseMarkup = true;
			this.frame4.LabelWidget = this.GtkLabel17;
			this.SourceVBox.Add (this.frame4);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.SourceVBox [this.frame4]));
			w7.Position = 1;
			this.notebook1.Add (this.SourceVBox);
			global::Gtk.Notebook.NotebookChild w8 = ((global::Gtk.Notebook.NotebookChild)(this.notebook1 [this.SourceVBox]));
			w8.MenuLabel = "";
			// Notebook tab
			this.label1 = new global::Gtk.Label ();
			this.label1.Name = "label1";
			this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("Source");
			this.notebook1.SetTabLabel (this.SourceVBox, this.label1);
			this.label1.ShowAll ();
			// Container child notebook1.Gtk.Notebook+NotebookChild
			this.VBoxcom = new global::Gtk.VBox ();
			this.VBoxcom.Name = "VBoxcom";
			this.VBoxcom.Spacing = 6;
			this.VBoxcom.BorderWidth = ((uint)(3));
			// Container child VBoxcom.Gtk.Box+BoxChild
			this.hbox9 = new global::Gtk.HBox ();
			this.hbox9.Name = "hbox9";
			this.hbox9.Spacing = 6;
			// Container child hbox9.Gtk.Box+BoxChild
			this.vbox4 = new global::Gtk.VBox ();
			this.vbox4.Name = "vbox4";
			this.vbox4.Spacing = 6;
			// Container child vbox4.Gtk.Box+BoxChild
			this.CompositionComboBox = global::Gtk.ComboBox.NewText ();
			this.CompositionComboBox.Name = "CompositionComboBox";
			this.vbox4.Add (this.CompositionComboBox);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.CompositionComboBox]));
			w9.Position = 0;
			w9.Expand = false;
			w9.Fill = false;
			this.hbox9.Add (this.vbox4);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.hbox9 [this.vbox4]));
			w10.Position = 0;
			w10.Expand = false;
			w10.Fill = false;
			// Container child hbox9.Gtk.Box+BoxChild
			this.CompositionInformationLabel = new global::Gtk.Label ();
			this.CompositionInformationLabel.Name = "CompositionInformationLabel";
			this.CompositionInformationLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("CompositionInformationLabel");
			this.CompositionInformationLabel.UseMarkup = true;
			this.CompositionInformationLabel.Wrap = true;
			this.CompositionInformationLabel.Selectable = true;
			this.hbox9.Add (this.CompositionInformationLabel);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.hbox9 [this.CompositionInformationLabel]));
			w11.Position = 1;
			this.VBoxcom.Add (this.hbox9);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.VBoxcom [this.hbox9]));
			w12.Position = 0;
			w12.Expand = false;
			w12.Fill = false;
			// Container child VBoxcom.Gtk.Box+BoxChild
			this.CompositionVBox1 = new global::Gtk.HBox ();
			this.CompositionVBox1.Name = "CompositionVBox1";
			this.CompositionVBox1.Spacing = 6;
			// Container child CompositionVBox1.Gtk.Box+BoxChild
			this.CompositionSettingsFrame = new global::Gtk.Frame ();
			this.CompositionSettingsFrame.Name = "CompositionSettingsFrame";
			this.CompositionSettingsFrame.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child CompositionSettingsFrame.Gtk.Container+ContainerChild
			this.CompositionSettingsPlace = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.CompositionSettingsPlace.Name = "CompositionSettingsPlace";
			this.CompositionSettingsPlace.LeftPadding = ((uint)(12));
			this.CompositionSettingsFrame.Add (this.CompositionSettingsPlace);
			this.GtkLabel16 = new global::Gtk.Label ();
			this.GtkLabel16.Name = "GtkLabel16";
			this.GtkLabel16.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Settings</b>");
			this.GtkLabel16.UseMarkup = true;
			this.CompositionSettingsFrame.LabelWidget = this.GtkLabel16;
			this.CompositionVBox1.Add (this.CompositionSettingsFrame);
			global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.CompositionVBox1 [this.CompositionSettingsFrame]));
			w14.Position = 0;
			// Container child CompositionVBox1.Gtk.Box+BoxChild
			this.frame2 = new global::Gtk.Frame ();
			this.frame2.Name = "frame2";
			this.frame2.ShadowType = ((global::Gtk.ShadowType)(2));
			// Container child frame2.Gtk.Container+ContainerChild
			this.GtkAlignment11 = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.GtkAlignment11.Name = "GtkAlignment11";
			this.GtkAlignment11.LeftPadding = ((uint)(12));
			// Container child GtkAlignment11.Gtk.Container+ContainerChild
			this.imagePreview = new global::Gtk.Image ();
			this.imagePreview.Name = "imagePreview";
			this.GtkAlignment11.Add (this.imagePreview);
			this.frame2.Add (this.GtkAlignment11);
			this.GtkLabel18 = new global::Gtk.Label ();
			this.GtkLabel18.Name = "GtkLabel18";
			this.GtkLabel18.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Preview</b>");
			this.GtkLabel18.UseMarkup = true;
			this.frame2.LabelWidget = this.GtkLabel18;
			this.CompositionVBox1.Add (this.frame2);
			global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.CompositionVBox1 [this.frame2]));
			w17.Position = 1;
			w17.Expand = false;
			w17.Fill = false;
			this.VBoxcom.Add (this.CompositionVBox1);
			global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.VBoxcom [this.CompositionVBox1]));
			w18.Position = 1;
			this.notebook1.Add (this.VBoxcom);
			global::Gtk.Notebook.NotebookChild w19 = ((global::Gtk.Notebook.NotebookChild)(this.notebook1 [this.VBoxcom]));
			w19.Position = 1;
			w19.MenuLabel = "";
			// Notebook tab
			this.label3 = new global::Gtk.Label ();
			this.label3.Name = "label3";
			this.label3.LabelProp = global::Mono.Unix.Catalog.GetString ("Composition");
			this.notebook1.SetTabLabel (this.VBoxcom, this.label3);
			this.label3.ShowAll ();
			// Container child notebook1.Gtk.Notebook+NotebookChild
			this.vbox5 = new global::Gtk.VBox ();
			this.vbox5.Name = "vbox5";
			this.vbox5.Spacing = 6;
			this.vbox5.BorderWidth = ((uint)(3));
			// Container child vbox5.Gtk.Box+BoxChild
			this.hbox2 = new global::Gtk.HBox ();
			this.hbox2.Name = "hbox2";
			this.hbox2.Spacing = 6;
			// Container child hbox2.Gtk.Box+BoxChild
			this.vbox7 = new global::Gtk.VBox ();
			this.vbox7.Name = "vbox7";
			this.vbox7.Spacing = 6;
			// Container child vbox7.Gtk.Box+BoxChild
			this.hbox10 = new global::Gtk.HBox ();
			this.hbox10.Name = "hbox10";
			this.hbox10.Spacing = 6;
			// Container child hbox10.Gtk.Box+BoxChild
			this.EffectsComboBox = global::Gtk.ComboBox.NewText ();
			this.EffectsComboBox.Name = "EffectsComboBox";
			this.hbox10.Add (this.EffectsComboBox);
			global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.hbox10 [this.EffectsComboBox]));
			w20.Position = 0;
			w20.Expand = false;
			w20.Fill = false;
			// Container child hbox10.Gtk.Box+BoxChild
			this.effectAddBtn = new global::Gtk.Button ();
			this.effectAddBtn.CanFocus = true;
			this.effectAddBtn.Name = "effectAddBtn";
			this.effectAddBtn.UseUnderline = true;
			// Container child effectAddBtn.Gtk.Container+ContainerChild
			global::Gtk.Alignment w21 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w22 = new global::Gtk.HBox ();
			w22.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w23 = new global::Gtk.Image ();
			w23.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-add", global::Gtk.IconSize.Menu);
			w22.Add (w23);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w25 = new global::Gtk.Label ();
			w25.LabelProp = global::Mono.Unix.Catalog.GetString ("Add");
			w25.UseUnderline = true;
			w22.Add (w25);
			w21.Add (w22);
			this.effectAddBtn.Add (w21);
			this.hbox10.Add (this.effectAddBtn);
			global::Gtk.Box.BoxChild w29 = ((global::Gtk.Box.BoxChild)(this.hbox10 [this.effectAddBtn]));
			w29.Position = 1;
			w29.Expand = false;
			w29.Fill = false;
			this.vbox7.Add (this.hbox10);
			global::Gtk.Box.BoxChild w30 = ((global::Gtk.Box.BoxChild)(this.vbox7 [this.hbox10]));
			w30.Position = 0;
			w30.Expand = false;
			w30.Fill = false;
			this.hbox2.Add (this.vbox7);
			global::Gtk.Box.BoxChild w31 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.vbox7]));
			w31.Position = 0;
			w31.Expand = false;
			w31.Fill = false;
			// Container child hbox2.Gtk.Box+BoxChild
			this.EffectInformationLabel = new global::Gtk.Label ();
			this.EffectInformationLabel.Name = "EffectInformationLabel";
			this.EffectInformationLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("EffectInformationLabel");
			this.EffectInformationLabel.UseMarkup = true;
			this.EffectInformationLabel.Wrap = true;
			this.EffectInformationLabel.Selectable = true;
			this.hbox2.Add (this.EffectInformationLabel);
			global::Gtk.Box.BoxChild w32 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.EffectInformationLabel]));
			w32.Position = 1;
			this.vbox5.Add (this.hbox2);
			global::Gtk.Box.BoxChild w33 = ((global::Gtk.Box.BoxChild)(this.vbox5 [this.hbox2]));
			w33.Position = 0;
			w33.Expand = false;
			w33.Fill = false;
			// Container child vbox5.Gtk.Box+BoxChild
			this.hbox3 = new global::Gtk.HBox ();
			this.hbox3.Name = "hbox3";
			this.hbox3.Spacing = 6;
			// Container child hbox3.Gtk.Box+BoxChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.EffectsList = new global::Gtk.TreeView ();
			this.EffectsList.CanFocus = true;
			this.EffectsList.Name = "EffectsList";
			this.GtkScrolledWindow.Add (this.EffectsList);
			this.hbox3.Add (this.GtkScrolledWindow);
			global::Gtk.Box.BoxChild w35 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.GtkScrolledWindow]));
			w35.Position = 0;
			// Container child hbox3.Gtk.Box+BoxChild
			this.vbuttonbox1 = new global::Gtk.VButtonBox ();
			this.vbuttonbox1.Name = "vbuttonbox1";
			this.vbuttonbox1.Spacing = 4;
			this.vbuttonbox1.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(3));
			// Container child vbuttonbox1.Gtk.ButtonBox+ButtonBoxChild
			this.editEffectBtn = new global::Gtk.Button ();
			this.editEffectBtn.Sensitive = false;
			this.editEffectBtn.CanFocus = true;
			this.editEffectBtn.Name = "editEffectBtn";
			this.editEffectBtn.UseUnderline = true;
			// Container child editEffectBtn.Gtk.Container+ContainerChild
			global::Gtk.Alignment w36 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w37 = new global::Gtk.HBox ();
			w37.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w38 = new global::Gtk.Image ();
			w38.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-edit", global::Gtk.IconSize.Menu);
			w37.Add (w38);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w40 = new global::Gtk.Label ();
			w40.LabelProp = global::Mono.Unix.Catalog.GetString ("_Edit");
			w40.UseUnderline = true;
			w37.Add (w40);
			w36.Add (w37);
			this.editEffectBtn.Add (w36);
			this.vbuttonbox1.Add (this.editEffectBtn);
			global::Gtk.ButtonBox.ButtonBoxChild w44 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.vbuttonbox1 [this.editEffectBtn]));
			w44.Expand = false;
			w44.Fill = false;
			// Container child vbuttonbox1.Gtk.ButtonBox+ButtonBoxChild
			this.upEffectBtn = new global::Gtk.Button ();
			this.upEffectBtn.Sensitive = false;
			this.upEffectBtn.CanFocus = true;
			this.upEffectBtn.Name = "upEffectBtn";
			this.upEffectBtn.UseUnderline = true;
			// Container child upEffectBtn.Gtk.Container+ContainerChild
			global::Gtk.Alignment w45 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w46 = new global::Gtk.HBox ();
			w46.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w47 = new global::Gtk.Image ();
			w47.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-go-up", global::Gtk.IconSize.Menu);
			w46.Add (w47);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w49 = new global::Gtk.Label ();
			w49.LabelProp = global::Mono.Unix.Catalog.GetString ("_Up");
			w49.UseUnderline = true;
			w46.Add (w49);
			w45.Add (w46);
			this.upEffectBtn.Add (w45);
			this.vbuttonbox1.Add (this.upEffectBtn);
			global::Gtk.ButtonBox.ButtonBoxChild w53 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.vbuttonbox1 [this.upEffectBtn]));
			w53.Position = 1;
			w53.Expand = false;
			w53.Fill = false;
			// Container child vbuttonbox1.Gtk.ButtonBox+ButtonBoxChild
			this.downEffectBtn = new global::Gtk.Button ();
			this.downEffectBtn.Sensitive = false;
			this.downEffectBtn.CanFocus = true;
			this.downEffectBtn.Name = "downEffectBtn";
			this.downEffectBtn.UseUnderline = true;
			// Container child downEffectBtn.Gtk.Container+ContainerChild
			global::Gtk.Alignment w54 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w55 = new global::Gtk.HBox ();
			w55.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w56 = new global::Gtk.Image ();
			w56.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-go-down", global::Gtk.IconSize.Menu);
			w55.Add (w56);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w58 = new global::Gtk.Label ();
			w58.LabelProp = global::Mono.Unix.Catalog.GetString ("Do_wn");
			w58.UseUnderline = true;
			w55.Add (w58);
			w54.Add (w55);
			this.downEffectBtn.Add (w54);
			this.vbuttonbox1.Add (this.downEffectBtn);
			global::Gtk.ButtonBox.ButtonBoxChild w62 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.vbuttonbox1 [this.downEffectBtn]));
			w62.Position = 2;
			w62.Expand = false;
			w62.Fill = false;
			// Container child vbuttonbox1.Gtk.ButtonBox+ButtonBoxChild
			this.cloneEffectBtn = new global::Gtk.Button ();
			this.cloneEffectBtn.Sensitive = false;
			this.cloneEffectBtn.CanFocus = true;
			this.cloneEffectBtn.Name = "cloneEffectBtn";
			this.cloneEffectBtn.UseUnderline = true;
			// Container child cloneEffectBtn.Gtk.Container+ContainerChild
			global::Gtk.Alignment w63 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w64 = new global::Gtk.HBox ();
			w64.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w65 = new global::Gtk.Image ();
			w65.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-copy", global::Gtk.IconSize.Menu);
			w64.Add (w65);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w67 = new global::Gtk.Label ();
			w67.LabelProp = global::Mono.Unix.Catalog.GetString ("_Clone");
			w67.UseUnderline = true;
			w64.Add (w67);
			w63.Add (w64);
			this.cloneEffectBtn.Add (w63);
			this.vbuttonbox1.Add (this.cloneEffectBtn);
			global::Gtk.ButtonBox.ButtonBoxChild w71 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.vbuttonbox1 [this.cloneEffectBtn]));
			w71.Position = 3;
			w71.Expand = false;
			w71.Fill = false;
			// Container child vbuttonbox1.Gtk.ButtonBox+ButtonBoxChild
			this.deleteEffectBtn = new global::Gtk.Button ();
			this.deleteEffectBtn.Sensitive = false;
			this.deleteEffectBtn.CanFocus = true;
			this.deleteEffectBtn.Name = "deleteEffectBtn";
			this.deleteEffectBtn.UseUnderline = true;
			// Container child deleteEffectBtn.Gtk.Container+ContainerChild
			global::Gtk.Alignment w72 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w73 = new global::Gtk.HBox ();
			w73.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w74 = new global::Gtk.Image ();
			w74.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-delete", global::Gtk.IconSize.Menu);
			w73.Add (w74);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w76 = new global::Gtk.Label ();
			w76.LabelProp = global::Mono.Unix.Catalog.GetString ("_Delete");
			w76.UseUnderline = true;
			w73.Add (w76);
			w72.Add (w73);
			this.deleteEffectBtn.Add (w72);
			this.vbuttonbox1.Add (this.deleteEffectBtn);
			global::Gtk.ButtonBox.ButtonBoxChild w80 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.vbuttonbox1 [this.deleteEffectBtn]));
			w80.Position = 4;
			w80.Expand = false;
			w80.Fill = false;
			this.hbox3.Add (this.vbuttonbox1);
			global::Gtk.Box.BoxChild w81 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.vbuttonbox1]));
			w81.Position = 1;
			w81.Expand = false;
			w81.Fill = false;
			this.vbox5.Add (this.hbox3);
			global::Gtk.Box.BoxChild w82 = ((global::Gtk.Box.BoxChild)(this.vbox5 [this.hbox3]));
			w82.Position = 1;
			this.notebook1.Add (this.vbox5);
			global::Gtk.Notebook.NotebookChild w83 = ((global::Gtk.Notebook.NotebookChild)(this.notebook1 [this.vbox5]));
			w83.Position = 2;
			w83.MenuLabel = "";
			// Notebook tab
			this.label5 = new global::Gtk.Label ();
			this.label5.Name = "label5";
			this.label5.LabelProp = global::Mono.Unix.Catalog.GetString ("Effects");
			this.notebook1.SetTabLabel (this.vbox5, this.label5);
			this.label5.ShowAll ();
			// Container child notebook1.Gtk.Notebook+NotebookChild
			this.vbox6 = new global::Gtk.VBox ();
			this.vbox6.Name = "vbox6";
			this.vbox6.Spacing = 6;
			this.vbox6.BorderWidth = ((uint)(3));
			// Container child vbox6.Gtk.Box+BoxChild
			this.frame3 = new global::Gtk.Frame ();
			this.frame3.Name = "frame3";
			this.frame3.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child frame3.Gtk.Container+ContainerChild
			this.GtkAlignment12 = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.GtkAlignment12.Name = "GtkAlignment12";
			this.GtkAlignment12.LeftPadding = ((uint)(12));
			// Container child GtkAlignment12.Gtk.Container+ContainerChild
			this.hbox5 = new global::Gtk.HBox ();
			this.hbox5.Name = "hbox5";
			this.hbox5.Spacing = 6;
			// Container child hbox5.Gtk.Box+BoxChild
			this.label9 = new global::Gtk.Label ();
			this.label9.Name = "label9";
			this.label9.LabelProp = global::Mono.Unix.Catalog.GetString ("Update interval:");
			this.hbox5.Add (this.label9);
			global::Gtk.Box.BoxChild w84 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.label9]));
			w84.Position = 0;
			w84.Expand = false;
			w84.Fill = false;
			// Container child hbox5.Gtk.Box+BoxChild
			this.vbox8 = new global::Gtk.VBox ();
			this.vbox8.Name = "vbox8";
			this.vbox8.Spacing = 6;
			// Container child vbox8.Gtk.Box+BoxChild
			this.IntervalLabel = new global::Gtk.Label ();
			this.IntervalLabel.Name = "IntervalLabel";
			this.IntervalLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("0 m");
			this.vbox8.Add (this.IntervalLabel);
			global::Gtk.Box.BoxChild w85 = ((global::Gtk.Box.BoxChild)(this.vbox8 [this.IntervalLabel]));
			w85.Position = 0;
			w85.Expand = false;
			w85.Fill = false;
			// Container child vbox8.Gtk.Box+BoxChild
			this.intervalScale = new global::Gtk.HScale (null);
			this.intervalScale.CanFocus = true;
			this.intervalScale.Name = "intervalScale";
			this.intervalScale.Adjustment.Lower = 1;
			this.intervalScale.Adjustment.Upper = 56;
			this.intervalScale.Adjustment.PageIncrement = 10;
			this.intervalScale.Adjustment.StepIncrement = 1;
			this.intervalScale.Adjustment.Value = 1;
			this.intervalScale.DrawValue = false;
			this.intervalScale.Digits = 0;
			this.intervalScale.ValuePos = ((global::Gtk.PositionType)(2));
			this.vbox8.Add (this.intervalScale);
			global::Gtk.Box.BoxChild w86 = ((global::Gtk.Box.BoxChild)(this.vbox8 [this.intervalScale]));
			w86.Position = 1;
			this.hbox5.Add (this.vbox8);
			global::Gtk.Box.BoxChild w87 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.vbox8]));
			w87.Position = 1;
			// Container child hbox5.Gtk.Box+BoxChild
			this.label11 = new global::Gtk.Label ();
			this.label11.Name = "label11";
			this.label11.LabelProp = global::Mono.Unix.Catalog.GetString ("Update Mode");
			this.hbox5.Add (this.label11);
			global::Gtk.Box.BoxChild w88 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.label11]));
			w88.Position = 2;
			w88.Expand = false;
			w88.Fill = false;
			// Container child hbox5.Gtk.Box+BoxChild
			this.UpdateIntervalModeCb = global::Gtk.ComboBox.NewText ();
			this.UpdateIntervalModeCb.AppendText (global::Mono.Unix.Catalog.GetString ("Updata on start"));
			this.UpdateIntervalModeCb.AppendText (global::Mono.Unix.Catalog.GetString ("Wait after start"));
			this.UpdateIntervalModeCb.AppendText (global::Mono.Unix.Catalog.GetString ("Wait from last update"));
			this.UpdateIntervalModeCb.Name = "UpdateIntervalModeCb";
			this.UpdateIntervalModeCb.Active = 1;
			this.hbox5.Add (this.UpdateIntervalModeCb);
			global::Gtk.Box.BoxChild w89 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.UpdateIntervalModeCb]));
			w89.Position = 3;
			w89.Expand = false;
			w89.Fill = false;
			this.GtkAlignment12.Add (this.hbox5);
			this.frame3.Add (this.GtkAlignment12);
			this.GtkLabel15 = new global::Gtk.Label ();
			this.GtkLabel15.Name = "GtkLabel15";
			this.GtkLabel15.LabelProp = global::Mono.Unix.Catalog.GetString ("Wallpaper update");
			this.GtkLabel15.UseMarkup = true;
			this.frame3.LabelWidget = this.GtkLabel15;
			this.vbox6.Add (this.frame3);
			global::Gtk.Box.BoxChild w92 = ((global::Gtk.Box.BoxChild)(this.vbox6 [this.frame3]));
			w92.Position = 0;
			w92.Expand = false;
			w92.Fill = false;
			// Container child vbox6.Gtk.Box+BoxChild
			this.frame5 = new global::Gtk.Frame ();
			this.frame5.Name = "frame5";
			this.frame5.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child frame5.Gtk.Container+ContainerChild
			this.GtkAlignment13 = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.GtkAlignment13.Name = "GtkAlignment13";
			this.GtkAlignment13.LeftPadding = ((uint)(12));
			// Container child GtkAlignment13.Gtk.Container+ContainerChild
			this.vbox9 = new global::Gtk.VBox ();
			this.vbox9.Name = "vbox9";
			this.vbox9.Spacing = 6;
			// Container child vbox9.Gtk.Box+BoxChild
			this.hbox4 = new global::Gtk.HBox ();
			this.hbox4.Name = "hbox4";
			this.hbox4.Spacing = 6;
			// Container child hbox4.Gtk.Box+BoxChild
			this.saveHistoryChBox = new global::Gtk.CheckButton ();
			this.saveHistoryChBox.CanFocus = true;
			this.saveHistoryChBox.Name = "saveHistoryChBox";
			this.saveHistoryChBox.Label = global::Mono.Unix.Catalog.GetString ("Save history");
			this.saveHistoryChBox.DrawIndicator = true;
			this.saveHistoryChBox.UseUnderline = true;
			this.hbox4.Add (this.saveHistoryChBox);
			global::Gtk.Box.BoxChild w93 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.saveHistoryChBox]));
			w93.Position = 0;
			// Container child hbox4.Gtk.Box+BoxChild
			this.selectSaveHostoryFolderBox = new global::Gtk.FileChooserButton (global::Mono.Unix.Catalog.GetString ("Выберите файл"), ((global::Gtk.FileChooserAction)(2)));
			this.selectSaveHostoryFolderBox.Sensitive = false;
			this.selectSaveHostoryFolderBox.Name = "selectSaveHostoryFolderBox";
			this.selectSaveHostoryFolderBox.ShowHidden = true;
			this.hbox4.Add (this.selectSaveHostoryFolderBox);
			global::Gtk.Box.BoxChild w94 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.selectSaveHostoryFolderBox]));
			w94.Position = 1;
			// Container child hbox4.Gtk.Box+BoxChild
			this.historyLimitSizeChBox = new global::Gtk.CheckButton ();
			this.historyLimitSizeChBox.Sensitive = false;
			this.historyLimitSizeChBox.CanFocus = true;
			this.historyLimitSizeChBox.Name = "historyLimitSizeChBox";
			this.historyLimitSizeChBox.Label = global::Mono.Unix.Catalog.GetString ("Max size");
			this.historyLimitSizeChBox.DrawIndicator = true;
			this.historyLimitSizeChBox.UseUnderline = true;
			this.hbox4.Add (this.historyLimitSizeChBox);
			global::Gtk.Box.BoxChild w95 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.historyLimitSizeChBox]));
			w95.Position = 2;
			// Container child hbox4.Gtk.Box+BoxChild
			this.historyMaxSizeSpin = new global::Gtk.SpinButton (0, 100, 1);
			this.historyMaxSizeSpin.Sensitive = false;
			this.historyMaxSizeSpin.CanFocus = true;
			this.historyMaxSizeSpin.Name = "historyMaxSizeSpin";
			this.historyMaxSizeSpin.Adjustment.PageIncrement = 10;
			this.historyMaxSizeSpin.ClimbRate = 1;
			this.historyMaxSizeSpin.Numeric = true;
			this.hbox4.Add (this.historyMaxSizeSpin);
			global::Gtk.Box.BoxChild w96 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.historyMaxSizeSpin]));
			w96.Position = 3;
			w96.Expand = false;
			w96.Fill = false;
			// Container child hbox4.Gtk.Box+BoxChild
			this.label8 = new global::Gtk.Label ();
			this.label8.Name = "label8";
			this.label8.LabelProp = global::Mono.Unix.Catalog.GetString ("Mb");
			this.hbox4.Add (this.label8);
			global::Gtk.Box.BoxChild w97 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.label8]));
			w97.Position = 4;
			w97.Expand = false;
			w97.Fill = false;
			this.vbox9.Add (this.hbox4);
			global::Gtk.Box.BoxChild w98 = ((global::Gtk.Box.BoxChild)(this.vbox9 [this.hbox4]));
			w98.Position = 0;
			w98.Expand = false;
			w98.Fill = false;
			// Container child vbox9.Gtk.Box+BoxChild
			this.hbox6 = new global::Gtk.HBox ();
			this.hbox6.Name = "hbox6";
			this.hbox6.Spacing = 6;
			// Container child hbox6.Gtk.Box+BoxChild
			this.saveTempImagesCb = new global::Gtk.CheckButton ();
			this.saveTempImagesCb.Sensitive = false;
			this.saveTempImagesCb.CanFocus = true;
			this.saveTempImagesCb.Name = "saveTempImagesCb";
			this.saveTempImagesCb.Label = global::Mono.Unix.Catalog.GetString ("Save intermediate images");
			this.saveTempImagesCb.DrawIndicator = true;
			this.saveTempImagesCb.UseUnderline = true;
			this.hbox6.Add (this.saveTempImagesCb);
			global::Gtk.Box.BoxChild w99 = ((global::Gtk.Box.BoxChild)(this.hbox6 [this.saveTempImagesCb]));
			w99.Position = 0;
			this.vbox9.Add (this.hbox6);
			global::Gtk.Box.BoxChild w100 = ((global::Gtk.Box.BoxChild)(this.vbox9 [this.hbox6]));
			w100.Position = 1;
			w100.Expand = false;
			w100.Fill = false;
			this.GtkAlignment13.Add (this.vbox9);
			this.frame5.Add (this.GtkAlignment13);
			this.GtkLabel20 = new global::Gtk.Label ();
			this.GtkLabel20.Name = "GtkLabel20";
			this.GtkLabel20.LabelProp = global::Mono.Unix.Catalog.GetString ("History");
			this.GtkLabel20.UseMarkup = true;
			this.frame5.LabelWidget = this.GtkLabel20;
			this.vbox6.Add (this.frame5);
			global::Gtk.Box.BoxChild w103 = ((global::Gtk.Box.BoxChild)(this.vbox6 [this.frame5]));
			w103.Position = 1;
			w103.Expand = false;
			w103.Fill = false;
			// Container child vbox6.Gtk.Box+BoxChild
			this.frame6 = new global::Gtk.Frame ();
			this.frame6.Name = "frame6";
			this.frame6.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child frame6.Gtk.Container+ContainerChild
			this.GtkAlignment14 = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.GtkAlignment14.Name = "GtkAlignment14";
			this.GtkAlignment14.LeftPadding = ((uint)(12));
			// Container child GtkAlignment14.Gtk.Container+ContainerChild
			this.vbox10 = new global::Gtk.VBox ();
			this.vbox10.Name = "vbox10";
			this.vbox10.Spacing = 6;
			// Container child vbox10.Gtk.Box+BoxChild
			this.hbox7 = new global::Gtk.HBox ();
			this.hbox7.Name = "hbox7";
			this.hbox7.Spacing = 6;
			// Container child hbox7.Gtk.Box+BoxChild
			this.label12 = new global::Gtk.Label ();
			this.label12.Name = "label12";
			this.label12.LabelProp = global::Mono.Unix.Catalog.GetString ("Language");
			this.hbox7.Add (this.label12);
			global::Gtk.Box.BoxChild w104 = ((global::Gtk.Box.BoxChild)(this.hbox7 [this.label12]));
			w104.Position = 0;
			w104.Expand = false;
			w104.Fill = false;
			// Container child hbox7.Gtk.Box+BoxChild
			this.languageCB = global::Gtk.ComboBox.NewText ();
			this.languageCB.Name = "languageCB";
			this.hbox7.Add (this.languageCB);
			global::Gtk.Box.BoxChild w105 = ((global::Gtk.Box.BoxChild)(this.hbox7 [this.languageCB]));
			w105.Position = 1;
			w105.Expand = false;
			this.vbox10.Add (this.hbox7);
			global::Gtk.Box.BoxChild w106 = ((global::Gtk.Box.BoxChild)(this.vbox10 [this.hbox7]));
			w106.Position = 0;
			w106.Expand = false;
			w106.Fill = false;
			// Container child vbox10.Gtk.Box+BoxChild
			this.checkbutton3 = new global::Gtk.CheckButton ();
			this.checkbutton3.CanFocus = true;
			this.checkbutton3.Name = "checkbutton3";
			this.checkbutton3.Label = global::Mono.Unix.Catalog.GetString ("Autorun");
			this.checkbutton3.DrawIndicator = true;
			this.checkbutton3.UseUnderline = true;
			this.vbox10.Add (this.checkbutton3);
			global::Gtk.Box.BoxChild w107 = ((global::Gtk.Box.BoxChild)(this.vbox10 [this.checkbutton3]));
			w107.Position = 1;
			w107.Expand = false;
			w107.Fill = false;
			this.GtkAlignment14.Add (this.vbox10);
			this.frame6.Add (this.GtkAlignment14);
			this.GtkLabel21 = new global::Gtk.Label ();
			this.GtkLabel21.Name = "GtkLabel21";
			this.GtkLabel21.LabelProp = global::Mono.Unix.Catalog.GetString ("Other");
			this.GtkLabel21.UseMarkup = true;
			this.frame6.LabelWidget = this.GtkLabel21;
			this.vbox6.Add (this.frame6);
			global::Gtk.Box.BoxChild w110 = ((global::Gtk.Box.BoxChild)(this.vbox6 [this.frame6]));
			w110.Position = 2;
			w110.Expand = false;
			w110.Fill = false;
			// Container child vbox6.Gtk.Box+BoxChild
			this.frame7 = new global::Gtk.Frame ();
			this.frame7.Name = "frame7";
			this.frame7.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child frame7.Gtk.Container+ContainerChild
			this.GtkAlignment15 = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.GtkAlignment15.Name = "GtkAlignment15";
			this.GtkAlignment15.LeftPadding = ((uint)(12));
			// Container child GtkAlignment15.Gtk.Container+ContainerChild
			this.table1 = new global::Gtk.Table (((uint)(3)), ((uint)(2)), false);
			this.table1.Name = "table1";
			this.table1.RowSpacing = ((uint)(6));
			this.table1.ColumnSpacing = ((uint)(6));
			// Container child table1.Gtk.Table+TableChild
			this.label2 = new global::Gtk.Label ();
			this.label2.Name = "label2";
			this.label2.LabelProp = global::Mono.Unix.Catalog.GetString ("Before change");
			this.table1.Add (this.label2);
			global::Gtk.Table.TableChild w111 = ((global::Gtk.Table.TableChild)(this.table1 [this.label2]));
			w111.XOptions = ((global::Gtk.AttachOptions)(4));
			w111.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.label4 = new global::Gtk.Label ();
			this.label4.Name = "label4";
			this.label4.LabelProp = global::Mono.Unix.Catalog.GetString ("After change");
			this.table1.Add (this.label4);
			global::Gtk.Table.TableChild w112 = ((global::Gtk.Table.TableChild)(this.table1 [this.label4]));
			w112.TopAttach = ((uint)(1));
			w112.BottomAttach = ((uint)(2));
			w112.XOptions = ((global::Gtk.AttachOptions)(4));
			w112.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.label6 = new global::Gtk.Label ();
			this.label6.Name = "label6";
			this.label6.LabelProp = global::Mono.Unix.Catalog.GetString ("Set wallpaper");
			this.table1.Add (this.label6);
			global::Gtk.Table.TableChild w113 = ((global::Gtk.Table.TableChild)(this.table1 [this.label6]));
			w113.TopAttach = ((uint)(2));
			w113.BottomAttach = ((uint)(3));
			w113.XOptions = ((global::Gtk.AttachOptions)(4));
			w113.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.scriptAfterCB = global::Gtk.ComboBox.NewText ();
			this.scriptAfterCB.Sensitive = false;
			this.scriptAfterCB.Name = "scriptAfterCB";
			this.table1.Add (this.scriptAfterCB);
			global::Gtk.Table.TableChild w114 = ((global::Gtk.Table.TableChild)(this.table1 [this.scriptAfterCB]));
			w114.TopAttach = ((uint)(1));
			w114.BottomAttach = ((uint)(2));
			w114.LeftAttach = ((uint)(1));
			w114.RightAttach = ((uint)(2));
			w114.XOptions = ((global::Gtk.AttachOptions)(4));
			w114.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.scriptBeforeCB = global::Gtk.ComboBox.NewText ();
			this.scriptBeforeCB.Sensitive = false;
			this.scriptBeforeCB.Name = "scriptBeforeCB";
			this.table1.Add (this.scriptBeforeCB);
			global::Gtk.Table.TableChild w115 = ((global::Gtk.Table.TableChild)(this.table1 [this.scriptBeforeCB]));
			w115.LeftAttach = ((uint)(1));
			w115.RightAttach = ((uint)(2));
			w115.XOptions = ((global::Gtk.AttachOptions)(4));
			w115.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.scriptChangeCB = global::Gtk.ComboBox.NewText ();
			this.scriptChangeCB.Name = "scriptChangeCB";
			this.table1.Add (this.scriptChangeCB);
			global::Gtk.Table.TableChild w116 = ((global::Gtk.Table.TableChild)(this.table1 [this.scriptChangeCB]));
			w116.TopAttach = ((uint)(2));
			w116.BottomAttach = ((uint)(3));
			w116.LeftAttach = ((uint)(1));
			w116.RightAttach = ((uint)(2));
			w116.XOptions = ((global::Gtk.AttachOptions)(4));
			w116.YOptions = ((global::Gtk.AttachOptions)(4));
			this.GtkAlignment15.Add (this.table1);
			this.frame7.Add (this.GtkAlignment15);
			this.GtkLabel22 = new global::Gtk.Label ();
			this.GtkLabel22.Name = "GtkLabel22";
			this.GtkLabel22.LabelProp = global::Mono.Unix.Catalog.GetString ("User scripts");
			this.GtkLabel22.UseMarkup = true;
			this.frame7.LabelWidget = this.GtkLabel22;
			this.vbox6.Add (this.frame7);
			global::Gtk.Box.BoxChild w119 = ((global::Gtk.Box.BoxChild)(this.vbox6 [this.frame7]));
			w119.Position = 3;
			w119.Expand = false;
			w119.Fill = false;
			this.notebook1.Add (this.vbox6);
			global::Gtk.Notebook.NotebookChild w120 = ((global::Gtk.Notebook.NotebookChild)(this.notebook1 [this.vbox6]));
			w120.Position = 3;
			w120.MenuLabel = "";
			// Notebook tab
			this.label7 = new global::Gtk.Label ();
			this.label7.Name = "label7";
			this.label7.LabelProp = global::Mono.Unix.Catalog.GetString ("Program");
			this.notebook1.SetTabLabel (this.vbox6, this.label7);
			this.label7.ShowAll ();
			this.vbox2.Add (this.notebook1);
			global::Gtk.Box.BoxChild w121 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.notebook1]));
			w121.Position = 0;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hseparator2 = new global::Gtk.HSeparator ();
			this.hseparator2.Name = "hseparator2";
			this.vbox2.Add (this.hseparator2);
			global::Gtk.Box.BoxChild w122 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hseparator2]));
			w122.Position = 1;
			w122.Expand = false;
			w122.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.frame1 = new global::Gtk.Frame ();
			this.frame1.Name = "frame1";
			this.frame1.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child frame1.Gtk.Container+ContainerChild
			this.GtkAlignment6 = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.GtkAlignment6.Name = "GtkAlignment6";
			this.GtkAlignment6.LeftPadding = ((uint)(12));
			// Container child GtkAlignment6.Gtk.Container+ContainerChild
			this.hbox1 = new global::Gtk.HBox ();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.ProfilesCb = global::Gtk.ComboBox.NewText ();
			this.ProfilesCb.CanFocus = true;
			this.ProfilesCb.Name = "ProfilesCb";
			this.hbox1.Add (this.ProfilesCb);
			global::Gtk.Box.BoxChild w123 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.ProfilesCb]));
			w123.Position = 0;
			// Container child hbox1.Gtk.Box+BoxChild
			this.hbuttonbox2 = new global::Gtk.HButtonBox ();
			this.hbuttonbox2.Name = "hbuttonbox2";
			this.hbuttonbox2.Spacing = 4;
			this.hbuttonbox2.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(4));
			// Container child hbuttonbox2.Gtk.ButtonBox+ButtonBoxChild
			this.applyProfileBtn = new global::Gtk.Button ();
			this.applyProfileBtn.Sensitive = false;
			this.applyProfileBtn.CanFocus = true;
			this.applyProfileBtn.Name = "applyProfileBtn";
			this.applyProfileBtn.UseUnderline = true;
			// Container child applyProfileBtn.Gtk.Container+ContainerChild
			global::Gtk.Alignment w124 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w125 = new global::Gtk.HBox ();
			w125.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w126 = new global::Gtk.Image ();
			w126.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-apply", global::Gtk.IconSize.Menu);
			w125.Add (w126);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w128 = new global::Gtk.Label ();
			w128.LabelProp = global::Mono.Unix.Catalog.GetString ("_Apply");
			w128.UseUnderline = true;
			w125.Add (w128);
			w124.Add (w125);
			this.applyProfileBtn.Add (w124);
			this.hbuttonbox2.Add (this.applyProfileBtn);
			global::Gtk.ButtonBox.ButtonBoxChild w132 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox2 [this.applyProfileBtn]));
			w132.Expand = false;
			w132.Fill = false;
			// Container child hbuttonbox2.Gtk.ButtonBox+ButtonBoxChild
			this.saveProfileBtn = new global::Gtk.Button ();
			this.saveProfileBtn.CanFocus = true;
			this.saveProfileBtn.Name = "saveProfileBtn";
			this.saveProfileBtn.UseUnderline = true;
			// Container child saveProfileBtn.Gtk.Container+ContainerChild
			global::Gtk.Alignment w133 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w134 = new global::Gtk.HBox ();
			w134.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w135 = new global::Gtk.Image ();
			w135.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-save", global::Gtk.IconSize.Menu);
			w134.Add (w135);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w137 = new global::Gtk.Label ();
			w137.LabelProp = global::Mono.Unix.Catalog.GetString ("_Save");
			w137.UseUnderline = true;
			w134.Add (w137);
			w133.Add (w134);
			this.saveProfileBtn.Add (w133);
			this.hbuttonbox2.Add (this.saveProfileBtn);
			global::Gtk.ButtonBox.ButtonBoxChild w141 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox2 [this.saveProfileBtn]));
			w141.Position = 1;
			w141.Expand = false;
			w141.Fill = false;
			// Container child hbuttonbox2.Gtk.ButtonBox+ButtonBoxChild
			this.deleteProfileBtn = new global::Gtk.Button ();
			this.deleteProfileBtn.Sensitive = false;
			this.deleteProfileBtn.CanFocus = true;
			this.deleteProfileBtn.Name = "deleteProfileBtn";
			this.deleteProfileBtn.UseUnderline = true;
			// Container child deleteProfileBtn.Gtk.Container+ContainerChild
			global::Gtk.Alignment w142 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w143 = new global::Gtk.HBox ();
			w143.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w144 = new global::Gtk.Image ();
			w144.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-delete", global::Gtk.IconSize.Menu);
			w143.Add (w144);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w146 = new global::Gtk.Label ();
			w146.LabelProp = global::Mono.Unix.Catalog.GetString ("_Delete");
			w146.UseUnderline = true;
			w143.Add (w146);
			w142.Add (w143);
			this.deleteProfileBtn.Add (w142);
			this.hbuttonbox2.Add (this.deleteProfileBtn);
			global::Gtk.ButtonBox.ButtonBoxChild w150 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox2 [this.deleteProfileBtn]));
			w150.Position = 2;
			w150.Expand = false;
			w150.Fill = false;
			this.hbox1.Add (this.hbuttonbox2);
			global::Gtk.Box.BoxChild w151 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.hbuttonbox2]));
			w151.Position = 1;
			w151.Expand = false;
			w151.Fill = false;
			this.GtkAlignment6.Add (this.hbox1);
			this.frame1.Add (this.GtkAlignment6);
			this.GtkLabel14 = new global::Gtk.Label ();
			this.GtkLabel14.Name = "GtkLabel14";
			this.GtkLabel14.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Profiles</b>");
			this.GtkLabel14.UseMarkup = true;
			this.frame1.LabelWidget = this.GtkLabel14;
			this.vbox2.Add (this.frame1);
			global::Gtk.Box.BoxChild w154 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.frame1]));
			w154.Position = 2;
			w154.Expand = false;
			w154.Fill = false;
			w1.Add (this.vbox2);
			global::Gtk.Box.BoxChild w155 = ((global::Gtk.Box.BoxChild)(w1 [this.vbox2]));
			w155.Position = 0;
			// Internal child DeMixer.ConfigDlg.ActionArea
			global::Gtk.HButtonBox w156 = this.ActionArea;
			w156.Name = "dialog1_ActionArea";
			w156.Spacing = 6;
			w156.BorderWidth = ((uint)(5));
			w156.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(4));
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.buttonOk = new global::Gtk.Button ();
			this.buttonOk.CanDefault = true;
			this.buttonOk.CanFocus = true;
			this.buttonOk.Name = "buttonOk";
			this.buttonOk.UseUnderline = true;
			// Container child buttonOk.Gtk.Container+ContainerChild
			global::Gtk.Alignment w157 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w158 = new global::Gtk.HBox ();
			w158.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w159 = new global::Gtk.Image ();
			w159.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-close", global::Gtk.IconSize.Menu);
			w158.Add (w159);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w161 = new global::Gtk.Label ();
			w161.LabelProp = global::Mono.Unix.Catalog.GetString ("_Close");
			w161.UseUnderline = true;
			w158.Add (w161);
			w157.Add (w158);
			this.buttonOk.Add (w157);
			this.AddActionWidget (this.buttonOk, -7);
			global::Gtk.ButtonBox.ButtonBoxChild w165 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w156 [this.buttonOk]));
			w165.Expand = false;
			w165.Fill = false;
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 587;
			this.DefaultHeight = 517;
			this.Show ();
			this.SourceCb.Changed += new global::System.EventHandler (this.OnSourceCbChanged);
			this.CompositionComboBox.Changed += new global::System.EventHandler (this.OnCompositionComboBoxChanged);
			this.EffectsComboBox.Changed += new global::System.EventHandler (this.OnEffectsComboBoxChanged);
			this.effectAddBtn.Clicked += new global::System.EventHandler (this.OnEffectAddBtnClicked);
			this.EffectsList.CursorChanged += new global::System.EventHandler (this.OnEffectsListCursorChanged);
			this.editEffectBtn.Clicked += new global::System.EventHandler (this.OnEditEffectBtnClicked);
			this.upEffectBtn.Clicked += new global::System.EventHandler (this.OnUpEffectBtnClicked);
			this.deleteEffectBtn.Clicked += new global::System.EventHandler (this.OnDeleteEffectBtnClicked);
			this.intervalScale.ChangeValue += new global::Gtk.ChangeValueHandler (this.OnIntervalScaleChangeValue);
			this.UpdateIntervalModeCb.Changed += new global::System.EventHandler (this.OnUpdateIntervalModeCbChanged);
			this.saveHistoryChBox.Clicked += new global::System.EventHandler (this.OnSaveHistoryChBoxClicked);
			this.selectSaveHostoryFolderBox.SelectionChanged += new global::System.EventHandler (this.OnSelectSaveHostoryFolderBoxSelectionChanged);
			this.historyLimitSizeChBox.Clicked += new global::System.EventHandler (this.OnHistoryLimitSizeChBoxClicked);
			this.historyMaxSizeSpin.ChangeValue += new global::Gtk.ChangeValueHandler (this.OnHistoryMaxSizeSpinChangeValue);
			this.saveTempImagesCb.Clicked += new global::System.EventHandler (this.OnSaveTempImagesCbClicked);
			this.languageCB.Changed += new global::System.EventHandler (this.OnLanguageCBChanged);
			this.scriptChangeCB.Changed += new global::System.EventHandler (this.OnScriptChangeCBChanged);
			this.scriptBeforeCB.Changed += new global::System.EventHandler (this.OnScriptBeforeCBChanged);
			this.scriptAfterCB.Changed += new global::System.EventHandler (this.OnScriptAfterCBChanged);
			this.ProfilesCb.Changed += new global::System.EventHandler (this.OnProfilesCbChanged);
			this.applyProfileBtn.Clicked += new global::System.EventHandler (this.OnApplyProfileBtnClicked);
			this.saveProfileBtn.Clicked += new global::System.EventHandler (this.OnsaveProfileBtnClicked);
			this.deleteProfileBtn.Clicked += new global::System.EventHandler (this.OnDeleteProfileBtnClicked);
			this.buttonOk.Clicked += new global::System.EventHandler (this.OnButtonOkClicked);
		}
	}
}
