
// This file has been generated by the GUI designer. Do not modify.
namespace DeMixer.Source.Konachan
{
	public partial class KonachanSourceConfigWiget
	{
		private global::Gtk.VBox vbox4;
		private global::Gtk.HBox hbox6;
		private global::Gtk.Label tagsLabel;
		private global::Gtk.Entry tagsEdit;
		private global::Gtk.Label ResultsCountLabel;
		private global::Gtk.HBox hbox3;
		private global::Gtk.Label label6;
		private global::Gtk.VBox vbox2;
		private global::Gtk.HBox tagsButtonsBox1;
		private global::Gtk.HBox tagsButtonsBox2;
		private global::Gtk.HBox tagsButtonsBox3;
		
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget DeMixer.Source.Konachan.KonachanSourceConfigWiget
			global::Stetic.BinContainer.Attach (this);
			this.Name = "DeMixer.Source.Konachan.KonachanSourceConfigWiget";
			// Container child DeMixer.Source.Konachan.KonachanSourceConfigWiget.Gtk.Container+ContainerChild
			this.vbox4 = new global::Gtk.VBox ();
			this.vbox4.Name = "vbox4";
			this.vbox4.Spacing = 6;
			// Container child vbox4.Gtk.Box+BoxChild
			this.hbox6 = new global::Gtk.HBox ();
			this.hbox6.Name = "hbox6";
			this.hbox6.Spacing = 6;
			// Container child hbox6.Gtk.Box+BoxChild
			this.tagsLabel = new global::Gtk.Label ();
			this.tagsLabel.Name = "tagsLabel";
			this.tagsLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("tags");
			this.hbox6.Add (this.tagsLabel);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox6 [this.tagsLabel]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child hbox6.Gtk.Box+BoxChild
			this.tagsEdit = new global::Gtk.Entry ();
			this.tagsEdit.CanFocus = true;
			this.tagsEdit.Name = "tagsEdit";
			this.tagsEdit.IsEditable = true;
			this.tagsEdit.InvisibleChar = '•';
			this.hbox6.Add (this.tagsEdit);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox6 [this.tagsEdit]));
			w2.Position = 1;
			// Container child hbox6.Gtk.Box+BoxChild
			this.ResultsCountLabel = new global::Gtk.Label ();
			this.ResultsCountLabel.Name = "ResultsCountLabel";
			this.hbox6.Add (this.ResultsCountLabel);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox6 [this.ResultsCountLabel]));
			w3.Position = 2;
			w3.Expand = false;
			w3.Fill = false;
			this.vbox4.Add (this.hbox6);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.hbox6]));
			w4.Position = 0;
			w4.Expand = false;
			w4.Fill = false;
			// Container child vbox4.Gtk.Box+BoxChild
			this.hbox3 = new global::Gtk.HBox ();
			this.hbox3.Name = "hbox3";
			this.hbox3.Spacing = 6;
			// Container child hbox3.Gtk.Box+BoxChild
			this.label6 = new global::Gtk.Label ();
			this.label6.Name = "label6";
			this.label6.LabelProp = global::Mono.Unix.Catalog.GetString ("Similar tags");
			this.hbox3.Add (this.label6);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.label6]));
			w5.Position = 0;
			w5.Expand = false;
			w5.Fill = false;
			// Container child hbox3.Gtk.Box+BoxChild
			this.vbox2 = new global::Gtk.VBox ();
			this.vbox2.Name = "vbox2";
			// Container child vbox2.Gtk.Box+BoxChild
			this.tagsButtonsBox1 = new global::Gtk.HBox ();
			this.tagsButtonsBox1.Name = "tagsButtonsBox1";
			this.vbox2.Add (this.tagsButtonsBox1);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.tagsButtonsBox1]));
			w6.Position = 0;
			w6.Expand = false;
			w6.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.tagsButtonsBox2 = new global::Gtk.HBox ();
			this.tagsButtonsBox2.Name = "tagsButtonsBox2";
			this.vbox2.Add (this.tagsButtonsBox2);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.tagsButtonsBox2]));
			w7.Position = 1;
			w7.Expand = false;
			w7.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.tagsButtonsBox3 = new global::Gtk.HBox ();
			this.tagsButtonsBox3.Name = "tagsButtonsBox3";
			this.vbox2.Add (this.tagsButtonsBox3);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.tagsButtonsBox3]));
			w8.Position = 2;
			w8.Expand = false;
			w8.Fill = false;
			this.hbox3.Add (this.vbox2);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.vbox2]));
			w9.Position = 1;
			this.vbox4.Add (this.hbox3);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.hbox3]));
			w10.Position = 1;
			w10.Expand = false;
			w10.Fill = false;
			this.Add (this.vbox4);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
			this.tagsEdit.Changed += new global::System.EventHandler (this.OnTagsEditChanged);
			this.tagsEdit.MoveCursor += new global::Gtk.MoveCursorHandler (this.OnTagsEditMoveCursor);
		}
	}
}
