// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace DeMixer.lib.std {
    
    
    public partial class googlecomSourcesConfigView {
        
        private Gtk.VBox vbox5;
        
        private Gtk.HBox hbox7;
        
        private Gtk.Label label5;
        
        private Gtk.Entry tagsEdit;
        
        private Gtk.ComboBox combobox1;
        
        private Gtk.HBox hbox8;
        
        private Gtk.Label size;
        
        private Gtk.ComboBox combobox2;
        
        private Gtk.Label label7;
        
        private Gtk.ComboBox combobox3;
        
        protected virtual void Build() {
            Stetic.Gui.Initialize(this);
            // Widget DeMixer.lib.std.googlecomSourcesConfigView
            Stetic.BinContainer.Attach(this);
            this.Name = "DeMixer.lib.std.googlecomSourcesConfigView";
            // Container child DeMixer.lib.std.googlecomSourcesConfigView.Gtk.Container+ContainerChild
            this.vbox5 = new Gtk.VBox();
            this.vbox5.Name = "vbox5";
            this.vbox5.Spacing = 6;
            // Container child vbox5.Gtk.Box+BoxChild
            this.hbox7 = new Gtk.HBox();
            this.hbox7.Name = "hbox7";
            this.hbox7.Spacing = 6;
            // Container child hbox7.Gtk.Box+BoxChild
            this.label5 = new Gtk.Label();
            this.label5.Name = "label5";
            this.label5.LabelProp = Mono.Unix.Catalog.GetString("responce");
            this.hbox7.Add(this.label5);
            Gtk.Box.BoxChild w1 = ((Gtk.Box.BoxChild)(this.hbox7[this.label5]));
            w1.Position = 0;
            w1.Expand = false;
            w1.Fill = false;
            // Container child hbox7.Gtk.Box+BoxChild
            this.tagsEdit = new Gtk.Entry();
            this.tagsEdit.CanFocus = true;
            this.tagsEdit.Name = "tagsEdit";
            this.tagsEdit.IsEditable = true;
            this.tagsEdit.InvisibleChar = '●';
            this.hbox7.Add(this.tagsEdit);
            Gtk.Box.BoxChild w2 = ((Gtk.Box.BoxChild)(this.hbox7[this.tagsEdit]));
            w2.Position = 1;
            // Container child hbox7.Gtk.Box+BoxChild
            this.combobox1 = Gtk.ComboBox.NewText();
            this.combobox1.AppendText(Mono.Unix.Catalog.GetString("<none>"));
            this.combobox1.AppendText(Mono.Unix.Catalog.GetString("add \"Desktop wallpaper\""));
            this.combobox1.Name = "combobox1";
            this.combobox1.Active = 0;
            this.hbox7.Add(this.combobox1);
            Gtk.Box.BoxChild w3 = ((Gtk.Box.BoxChild)(this.hbox7[this.combobox1]));
            w3.Position = 2;
            w3.Expand = false;
            w3.Fill = false;
            this.vbox5.Add(this.hbox7);
            Gtk.Box.BoxChild w4 = ((Gtk.Box.BoxChild)(this.vbox5[this.hbox7]));
            w4.Position = 0;
            w4.Expand = false;
            w4.Fill = false;
            // Container child vbox5.Gtk.Box+BoxChild
            this.hbox8 = new Gtk.HBox();
            this.hbox8.Name = "hbox8";
            this.hbox8.Spacing = 6;
            // Container child hbox8.Gtk.Box+BoxChild
            this.size = new Gtk.Label();
            this.size.Name = "size";
            this.size.LabelProp = Mono.Unix.Catalog.GetString("size");
            this.hbox8.Add(this.size);
            Gtk.Box.BoxChild w5 = ((Gtk.Box.BoxChild)(this.hbox8[this.size]));
            w5.Position = 0;
            w5.Expand = false;
            w5.Fill = false;
            // Container child hbox8.Gtk.Box+BoxChild
            this.combobox2 = Gtk.ComboBox.NewText();
            this.combobox2.AppendText(Mono.Unix.Catalog.GetString("Large"));
            this.combobox2.AppendText(Mono.Unix.Catalog.GetString("XLarge"));
            this.combobox2.AppendText(Mono.Unix.Catalog.GetString("XXLarge"));
            this.combobox2.AppendText(Mono.Unix.Catalog.GetString("Hude"));
            this.combobox2.Name = "combobox2";
            this.combobox2.Active = 0;
            this.hbox8.Add(this.combobox2);
            Gtk.Box.BoxChild w6 = ((Gtk.Box.BoxChild)(this.hbox8[this.combobox2]));
            w6.Position = 1;
            w6.Expand = false;
            w6.Fill = false;
            // Container child hbox8.Gtk.Box+BoxChild
            this.label7 = new Gtk.Label();
            this.label7.Name = "label7";
            this.label7.LabelProp = Mono.Unix.Catalog.GetString("color");
            this.hbox8.Add(this.label7);
            Gtk.Box.BoxChild w7 = ((Gtk.Box.BoxChild)(this.hbox8[this.label7]));
            w7.Position = 2;
            w7.Expand = false;
            w7.Fill = false;
            // Container child hbox8.Gtk.Box+BoxChild
            this.combobox3 = Gtk.ComboBox.NewText();
            this.combobox3.AppendText(Mono.Unix.Catalog.GetString("All"));
            this.combobox3.AppendText(Mono.Unix.Catalog.GetString("Red"));
            this.combobox3.AppendText(Mono.Unix.Catalog.GetString("Orange"));
            this.combobox3.AppendText(Mono.Unix.Catalog.GetString("Yellow"));
            this.combobox3.AppendText(Mono.Unix.Catalog.GetString("Green"));
            this.combobox3.AppendText(Mono.Unix.Catalog.GetString("Aqua"));
            this.combobox3.AppendText(Mono.Unix.Catalog.GetString("Blue"));
            this.combobox3.AppendText(Mono.Unix.Catalog.GetString("Purple"));
            this.combobox3.AppendText(Mono.Unix.Catalog.GetString("Pink"));
            this.combobox3.AppendText(Mono.Unix.Catalog.GetString("White"));
            this.combobox3.AppendText(Mono.Unix.Catalog.GetString("Gray"));
            this.combobox3.AppendText(Mono.Unix.Catalog.GetString("Black"));
            this.combobox3.AppendText(Mono.Unix.Catalog.GetString("Brown"));
            this.combobox3.Name = "combobox3";
            this.combobox3.Active = 0;
            this.hbox8.Add(this.combobox3);
            Gtk.Box.BoxChild w8 = ((Gtk.Box.BoxChild)(this.hbox8[this.combobox3]));
            w8.Position = 3;
            w8.Expand = false;
            w8.Fill = false;
            this.vbox5.Add(this.hbox8);
            Gtk.Box.BoxChild w9 = ((Gtk.Box.BoxChild)(this.vbox5[this.hbox8]));
            w9.Position = 1;
            w9.Expand = false;
            w9.Fill = false;
            this.Add(this.vbox5);
            if ((this.Child != null)) {
                this.Child.ShowAll();
            }
            this.Hide();
            this.tagsEdit.Changed += new System.EventHandler(this.OnTagsEditChanged);
        }
    }
}
