
// This file has been generated by the GUI designer. Do not modify.
namespace DeMixer.lib.std
{
	public partial class DirectorySourceConfigView
	{
		private global::Gtk.HBox hbox1;
		private global::Gtk.ScrolledWindow GtkScrolledWindow;
		private global::Gtk.TreeView FoldersList;
		private global::Gtk.VButtonBox vbuttonbox1;
		private global::Gtk.Button folderAddBtn;
		private global::Gtk.Button folderDeleteBtn;
		
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget DeMixer.lib.std.DirectorySourceConfigView
			global::Stetic.BinContainer.Attach (this);
			this.Name = "DeMixer.lib.std.DirectorySourceConfigView";
			// Container child DeMixer.lib.std.DirectorySourceConfigView.Gtk.Container+ContainerChild
			this.hbox1 = new global::Gtk.HBox ();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.FoldersList = new global::Gtk.TreeView ();
			this.FoldersList.CanFocus = true;
			this.FoldersList.Name = "FoldersList";
			this.GtkScrolledWindow.Add (this.FoldersList);
			this.hbox1.Add (this.GtkScrolledWindow);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.GtkScrolledWindow]));
			w2.Position = 0;
			// Container child hbox1.Gtk.Box+BoxChild
			this.vbuttonbox1 = new global::Gtk.VButtonBox ();
			this.vbuttonbox1.Name = "vbuttonbox1";
			this.vbuttonbox1.Spacing = 4;
			this.vbuttonbox1.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(3));
			// Container child vbuttonbox1.Gtk.ButtonBox+ButtonBoxChild
			this.folderAddBtn = new global::Gtk.Button ();
			this.folderAddBtn.CanFocus = true;
			this.folderAddBtn.Name = "folderAddBtn";
			this.folderAddBtn.UseUnderline = true;
			// Container child folderAddBtn.Gtk.Container+ContainerChild
			global::Gtk.Alignment w3 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w4 = new global::Gtk.HBox ();
			w4.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w5 = new global::Gtk.Image ();
			w5.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-add", global::Gtk.IconSize.Menu);
			w4.Add (w5);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w7 = new global::Gtk.Label ();
			w7.LabelProp = global::Mono.Unix.Catalog.GetString ("_Add");
			w7.UseUnderline = true;
			w4.Add (w7);
			w3.Add (w4);
			this.folderAddBtn.Add (w3);
			this.vbuttonbox1.Add (this.folderAddBtn);
			global::Gtk.ButtonBox.ButtonBoxChild w11 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.vbuttonbox1 [this.folderAddBtn]));
			w11.Expand = false;
			w11.Fill = false;
			// Container child vbuttonbox1.Gtk.ButtonBox+ButtonBoxChild
			this.folderDeleteBtn = new global::Gtk.Button ();
			this.folderDeleteBtn.CanFocus = true;
			this.folderDeleteBtn.Name = "folderDeleteBtn";
			this.folderDeleteBtn.UseUnderline = true;
			// Container child folderDeleteBtn.Gtk.Container+ContainerChild
			global::Gtk.Alignment w12 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w13 = new global::Gtk.HBox ();
			w13.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w14 = new global::Gtk.Image ();
			w14.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-delete", global::Gtk.IconSize.Menu);
			w13.Add (w14);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w16 = new global::Gtk.Label ();
			w16.LabelProp = global::Mono.Unix.Catalog.GetString ("_Delete");
			w16.UseUnderline = true;
			w13.Add (w16);
			w12.Add (w13);
			this.folderDeleteBtn.Add (w12);
			this.vbuttonbox1.Add (this.folderDeleteBtn);
			global::Gtk.ButtonBox.ButtonBoxChild w20 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.vbuttonbox1 [this.folderDeleteBtn]));
			w20.Position = 1;
			w20.Expand = false;
			w20.Fill = false;
			this.hbox1.Add (this.vbuttonbox1);
			global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.vbuttonbox1]));
			w21.Position = 1;
			w21.Expand = false;
			w21.Fill = false;
			this.Add (this.hbox1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
			this.folderAddBtn.Clicked += new global::System.EventHandler (this.OnFolderAddBtnClicked);
			this.folderDeleteBtn.Clicked += new global::System.EventHandler (this.OnFolderDeleteBtnClicked);
		}
	}
}
