
// This file has been generated by the GUI designer. Do not modify.
namespace DeMixer.lib.std
{
	public partial class EffectShadowDialog
	{
		private global::Gtk.VBox vbox2;
		private global::Gtk.Frame frame1;
		private global::Gtk.Alignment GtkAlignment2;
		private global::Gtk.Table table1;
		private global::Gtk.CheckButton checkbAbove;
		private global::Gtk.CheckButton checkbBelow;
		private global::Gtk.CheckButton checkbLeft;
		private global::Gtk.CheckButton checkbRight;
		private global::Gtk.Label GtkLabel6;
		private global::Gtk.Frame frame2;
		private global::Gtk.Alignment GtkAlignment3;
		private global::Gtk.VBox vbox3;
		private global::Gtk.HBox hbox3;
		private global::Gtk.Label label5;
		private global::Gtk.HScale hscaleSize;
		private global::Gtk.Table table2;
		private global::Gtk.CheckButton checkbSyncColor;
		private global::Gtk.ColorButton colorbuttonEnd;
		private global::Gtk.ColorButton colorbuttonStart;
		private global::Gtk.HScale hscaleTransparentEnd;
		private global::Gtk.HScale hscaleTransparentStart;
		private global::Gtk.Label label3;
		private global::Gtk.Label label4;
		private global::Gtk.Label GtkLabel7;
		private global::Gtk.Button buttonCancel;
		private global::Gtk.Button buttonOk;
		
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget DeMixer.lib.std.EffectShadowDialog
			this.Name = "DeMixer.lib.std.EffectShadowDialog";
			this.Title = global::Mono.Unix.Catalog.GetString ("Shadow effect");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Internal child DeMixer.lib.std.EffectShadowDialog.VBox
			global::Gtk.VBox w1 = this.VBox;
			w1.Name = "dialog1_VBox";
			w1.BorderWidth = ((uint)(2));
			// Container child dialog1_VBox.Gtk.Box+BoxChild
			this.vbox2 = new global::Gtk.VBox ();
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 6;
			// Container child vbox2.Gtk.Box+BoxChild
			this.frame1 = new global::Gtk.Frame ();
			this.frame1.Name = "frame1";
			this.frame1.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child frame1.Gtk.Container+ContainerChild
			this.GtkAlignment2 = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.GtkAlignment2.Name = "GtkAlignment2";
			this.GtkAlignment2.LeftPadding = ((uint)(12));
			// Container child GtkAlignment2.Gtk.Container+ContainerChild
			this.table1 = new global::Gtk.Table (((uint)(3)), ((uint)(3)), false);
			this.table1.Name = "table1";
			this.table1.RowSpacing = ((uint)(6));
			this.table1.ColumnSpacing = ((uint)(6));
			// Container child table1.Gtk.Table+TableChild
			this.checkbAbove = new global::Gtk.CheckButton ();
			this.checkbAbove.CanFocus = true;
			this.checkbAbove.Name = "checkbAbove";
			this.checkbAbove.Label = global::Mono.Unix.Catalog.GetString ("From above");
			this.checkbAbove.DrawIndicator = true;
			this.checkbAbove.UseUnderline = true;
			this.table1.Add (this.checkbAbove);
			global::Gtk.Table.TableChild w2 = ((global::Gtk.Table.TableChild)(this.table1 [this.checkbAbove]));
			w2.LeftAttach = ((uint)(1));
			w2.RightAttach = ((uint)(2));
			w2.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.checkbBelow = new global::Gtk.CheckButton ();
			this.checkbBelow.CanFocus = true;
			this.checkbBelow.Name = "checkbBelow";
			this.checkbBelow.Label = global::Mono.Unix.Catalog.GetString ("From below");
			this.checkbBelow.DrawIndicator = true;
			this.checkbBelow.UseUnderline = true;
			this.table1.Add (this.checkbBelow);
			global::Gtk.Table.TableChild w3 = ((global::Gtk.Table.TableChild)(this.table1 [this.checkbBelow]));
			w3.TopAttach = ((uint)(2));
			w3.BottomAttach = ((uint)(3));
			w3.LeftAttach = ((uint)(1));
			w3.RightAttach = ((uint)(2));
			w3.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.checkbLeft = new global::Gtk.CheckButton ();
			this.checkbLeft.CanFocus = true;
			this.checkbLeft.Name = "checkbLeft";
			this.checkbLeft.Label = global::Mono.Unix.Catalog.GetString ("From left");
			this.checkbLeft.DrawIndicator = true;
			this.checkbLeft.UseUnderline = true;
			this.table1.Add (this.checkbLeft);
			global::Gtk.Table.TableChild w4 = ((global::Gtk.Table.TableChild)(this.table1 [this.checkbLeft]));
			w4.TopAttach = ((uint)(1));
			w4.BottomAttach = ((uint)(2));
			w4.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.checkbRight = new global::Gtk.CheckButton ();
			this.checkbRight.CanFocus = true;
			this.checkbRight.Name = "checkbRight";
			this.checkbRight.Label = global::Mono.Unix.Catalog.GetString ("From right");
			this.checkbRight.DrawIndicator = true;
			this.checkbRight.UseUnderline = true;
			this.table1.Add (this.checkbRight);
			global::Gtk.Table.TableChild w5 = ((global::Gtk.Table.TableChild)(this.table1 [this.checkbRight]));
			w5.TopAttach = ((uint)(1));
			w5.BottomAttach = ((uint)(2));
			w5.LeftAttach = ((uint)(2));
			w5.RightAttach = ((uint)(3));
			w5.YOptions = ((global::Gtk.AttachOptions)(4));
			this.GtkAlignment2.Add (this.table1);
			this.frame1.Add (this.GtkAlignment2);
			this.GtkLabel6 = new global::Gtk.Label ();
			this.GtkLabel6.Name = "GtkLabel6";
			this.GtkLabel6.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Borders</b>");
			this.GtkLabel6.UseMarkup = true;
			this.frame1.LabelWidget = this.GtkLabel6;
			this.vbox2.Add (this.frame1);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.frame1]));
			w8.Position = 0;
			w8.Expand = false;
			w8.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.frame2 = new global::Gtk.Frame ();
			this.frame2.Name = "frame2";
			this.frame2.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child frame2.Gtk.Container+ContainerChild
			this.GtkAlignment3 = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.GtkAlignment3.Name = "GtkAlignment3";
			this.GtkAlignment3.LeftPadding = ((uint)(12));
			// Container child GtkAlignment3.Gtk.Container+ContainerChild
			this.vbox3 = new global::Gtk.VBox ();
			this.vbox3.Name = "vbox3";
			this.vbox3.Spacing = 6;
			// Container child vbox3.Gtk.Box+BoxChild
			this.hbox3 = new global::Gtk.HBox ();
			this.hbox3.Name = "hbox3";
			this.hbox3.Spacing = 6;
			// Container child hbox3.Gtk.Box+BoxChild
			this.label5 = new global::Gtk.Label ();
			this.label5.Name = "label5";
			this.label5.LabelProp = global::Mono.Unix.Catalog.GetString ("Size");
			this.hbox3.Add (this.label5);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.label5]));
			w9.Position = 0;
			w9.Expand = false;
			w9.Fill = false;
			// Container child hbox3.Gtk.Box+BoxChild
			this.hscaleSize = new global::Gtk.HScale (null);
			this.hscaleSize.CanFocus = true;
			this.hscaleSize.Name = "hscaleSize";
			this.hscaleSize.Adjustment.Upper = 100;
			this.hscaleSize.Adjustment.PageIncrement = 10;
			this.hscaleSize.Adjustment.StepIncrement = 1;
			this.hscaleSize.DrawValue = true;
			this.hscaleSize.Digits = 0;
			this.hscaleSize.ValuePos = ((global::Gtk.PositionType)(2));
			this.hbox3.Add (this.hscaleSize);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.hscaleSize]));
			w10.Position = 1;
			this.vbox3.Add (this.hbox3);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.hbox3]));
			w11.Position = 0;
			w11.Expand = false;
			w11.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.table2 = new global::Gtk.Table (((uint)(3)), ((uint)(3)), false);
			this.table2.Name = "table2";
			this.table2.RowSpacing = ((uint)(6));
			this.table2.ColumnSpacing = ((uint)(6));
			// Container child table2.Gtk.Table+TableChild
			this.checkbSyncColor = new global::Gtk.CheckButton ();
			this.checkbSyncColor.CanFocus = true;
			this.checkbSyncColor.Name = "checkbSyncColor";
			this.checkbSyncColor.Label = global::Mono.Unix.Catalog.GetString ("Sync colors");
			this.checkbSyncColor.DrawIndicator = true;
			this.checkbSyncColor.UseUnderline = true;
			this.table2.Add (this.checkbSyncColor);
			global::Gtk.Table.TableChild w12 = ((global::Gtk.Table.TableChild)(this.table2 [this.checkbSyncColor]));
			w12.TopAttach = ((uint)(2));
			w12.BottomAttach = ((uint)(3));
			w12.LeftAttach = ((uint)(1));
			w12.RightAttach = ((uint)(2));
			w12.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.colorbuttonEnd = new global::Gtk.ColorButton ();
			this.colorbuttonEnd.CanFocus = true;
			this.colorbuttonEnd.Events = ((global::Gdk.EventMask)(784));
			this.colorbuttonEnd.Name = "colorbuttonEnd";
			this.table2.Add (this.colorbuttonEnd);
			global::Gtk.Table.TableChild w13 = ((global::Gtk.Table.TableChild)(this.table2 [this.colorbuttonEnd]));
			w13.TopAttach = ((uint)(1));
			w13.BottomAttach = ((uint)(2));
			w13.LeftAttach = ((uint)(1));
			w13.RightAttach = ((uint)(2));
			w13.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.colorbuttonStart = new global::Gtk.ColorButton ();
			this.colorbuttonStart.CanFocus = true;
			this.colorbuttonStart.Events = ((global::Gdk.EventMask)(784));
			this.colorbuttonStart.Name = "colorbuttonStart";
			this.table2.Add (this.colorbuttonStart);
			global::Gtk.Table.TableChild w14 = ((global::Gtk.Table.TableChild)(this.table2 [this.colorbuttonStart]));
			w14.LeftAttach = ((uint)(1));
			w14.RightAttach = ((uint)(2));
			w14.XOptions = ((global::Gtk.AttachOptions)(4));
			w14.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.hscaleTransparentEnd = new global::Gtk.HScale (null);
			this.hscaleTransparentEnd.CanFocus = true;
			this.hscaleTransparentEnd.Name = "hscaleTransparentEnd";
			this.hscaleTransparentEnd.Adjustment.Upper = 100;
			this.hscaleTransparentEnd.Adjustment.PageIncrement = 10;
			this.hscaleTransparentEnd.Adjustment.StepIncrement = 1;
			this.hscaleTransparentEnd.DrawValue = true;
			this.hscaleTransparentEnd.Digits = 0;
			this.hscaleTransparentEnd.ValuePos = ((global::Gtk.PositionType)(2));
			this.table2.Add (this.hscaleTransparentEnd);
			global::Gtk.Table.TableChild w15 = ((global::Gtk.Table.TableChild)(this.table2 [this.hscaleTransparentEnd]));
			w15.TopAttach = ((uint)(1));
			w15.BottomAttach = ((uint)(2));
			w15.LeftAttach = ((uint)(2));
			w15.RightAttach = ((uint)(3));
			w15.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.hscaleTransparentStart = new global::Gtk.HScale (null);
			this.hscaleTransparentStart.CanFocus = true;
			this.hscaleTransparentStart.Name = "hscaleTransparentStart";
			this.hscaleTransparentStart.Adjustment.Upper = 100;
			this.hscaleTransparentStart.Adjustment.PageIncrement = 10;
			this.hscaleTransparentStart.Adjustment.StepIncrement = 1;
			this.hscaleTransparentStart.DrawValue = true;
			this.hscaleTransparentStart.Digits = 0;
			this.hscaleTransparentStart.ValuePos = ((global::Gtk.PositionType)(2));
			this.table2.Add (this.hscaleTransparentStart);
			global::Gtk.Table.TableChild w16 = ((global::Gtk.Table.TableChild)(this.table2 [this.hscaleTransparentStart]));
			w16.LeftAttach = ((uint)(2));
			w16.RightAttach = ((uint)(3));
			w16.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.label3 = new global::Gtk.Label ();
			this.label3.Name = "label3";
			this.label3.LabelProp = global::Mono.Unix.Catalog.GetString ("Start");
			this.table2.Add (this.label3);
			global::Gtk.Table.TableChild w17 = ((global::Gtk.Table.TableChild)(this.table2 [this.label3]));
			w17.XOptions = ((global::Gtk.AttachOptions)(4));
			w17.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.label4 = new global::Gtk.Label ();
			this.label4.Name = "label4";
			this.label4.LabelProp = global::Mono.Unix.Catalog.GetString ("End");
			this.table2.Add (this.label4);
			global::Gtk.Table.TableChild w18 = ((global::Gtk.Table.TableChild)(this.table2 [this.label4]));
			w18.TopAttach = ((uint)(1));
			w18.BottomAttach = ((uint)(2));
			w18.XOptions = ((global::Gtk.AttachOptions)(4));
			w18.YOptions = ((global::Gtk.AttachOptions)(4));
			this.vbox3.Add (this.table2);
			global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.table2]));
			w19.Position = 1;
			w19.Expand = false;
			w19.Fill = false;
			this.GtkAlignment3.Add (this.vbox3);
			this.frame2.Add (this.GtkAlignment3);
			this.GtkLabel7 = new global::Gtk.Label ();
			this.GtkLabel7.Name = "GtkLabel7";
			this.GtkLabel7.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Gradient</b>");
			this.GtkLabel7.UseMarkup = true;
			this.frame2.LabelWidget = this.GtkLabel7;
			this.vbox2.Add (this.frame2);
			global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.frame2]));
			w22.Position = 1;
			w22.Expand = false;
			w22.Fill = false;
			w1.Add (this.vbox2);
			global::Gtk.Box.BoxChild w23 = ((global::Gtk.Box.BoxChild)(w1 [this.vbox2]));
			w23.Position = 0;
			w23.Expand = false;
			w23.Fill = false;
			// Internal child DeMixer.lib.std.EffectShadowDialog.ActionArea
			global::Gtk.HButtonBox w24 = this.ActionArea;
			w24.Name = "dialog1_ActionArea";
			w24.Spacing = 10;
			w24.BorderWidth = ((uint)(5));
			w24.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(4));
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.buttonCancel = new global::Gtk.Button ();
			this.buttonCancel.CanDefault = true;
			this.buttonCancel.CanFocus = true;
			this.buttonCancel.Name = "buttonCancel";
			this.buttonCancel.UseStock = true;
			this.buttonCancel.UseUnderline = true;
			this.buttonCancel.Label = "gtk-cancel";
			this.AddActionWidget (this.buttonCancel, -6);
			global::Gtk.ButtonBox.ButtonBoxChild w25 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w24 [this.buttonCancel]));
			w25.Expand = false;
			w25.Fill = false;
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.buttonOk = new global::Gtk.Button ();
			this.buttonOk.CanDefault = true;
			this.buttonOk.CanFocus = true;
			this.buttonOk.Name = "buttonOk";
			this.buttonOk.UseStock = true;
			this.buttonOk.UseUnderline = true;
			this.buttonOk.Label = "gtk-ok";
			this.AddActionWidget (this.buttonOk, -5);
			global::Gtk.ButtonBox.ButtonBoxChild w26 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w24 [this.buttonOk]));
			w26.Position = 1;
			w26.Expand = false;
			w26.Fill = false;
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 400;
			this.DefaultHeight = 358;
			this.Show ();
			this.colorbuttonStart.ColorSet += new global::System.EventHandler (this.OnColorbuttonStartColorSet);
			this.colorbuttonEnd.ColorSet += new global::System.EventHandler (this.OnColorbuttonEndColorSet);
			this.checkbSyncColor.Toggled += new global::System.EventHandler (this.OnCheckbSyncColorToggled);
			this.buttonOk.Clicked += new global::System.EventHandler (this.OnButtonOkClicked);
		}
	}
}
