// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace DeMixer {
    
    
    public partial class ConfigDlg {
        
        private Gtk.VBox vbox2;
        
        private Gtk.Notebook notebook1;
        
        private Gtk.VBox SourceVBox;
        
        private Gtk.HBox hbox8;
        
        private Gtk.VBox vbox3;
        
        private Gtk.ComboBox SourceComboBox;
        
        private Gtk.Label SourceInformationLabel;
        
        private Gtk.Label label1;
        
        private Gtk.VBox CompositionVBox;
        
        private Gtk.HBox hbox9;
        
        private Gtk.VBox vbox4;
        
        private Gtk.ComboBox CompositionComboBox;
        
        private Gtk.Label CompositionInformationLabel;
        
        private Gtk.Label label3;
        
        private Gtk.VBox vbox5;
        
        private Gtk.HBox hbox2;
        
        private Gtk.VBox vbox7;
        
        private Gtk.HBox hbox10;
        
        private Gtk.ComboBox EffectsComboBox;
        
        private Gtk.Button button37;
        
        private Gtk.Label EffectInformationLabel;
        
        private Gtk.HBox hbox3;
        
        private Gtk.IconView iconview1;
        
        private Gtk.VButtonBox vbuttonbox1;
        
        private Gtk.Button button38;
        
        private Gtk.Button button39;
        
        private Gtk.Button button40;
        
        private Gtk.Button button41;
        
        private Gtk.Button button42;
        
        private Gtk.Label label5;
        
        private Gtk.VBox vbox6;
        
        private Gtk.HBox hbox4;
        
        private Gtk.CheckButton checkbutton1;
        
        private Gtk.FileChooserButton filechooserbutton1;
        
        private Gtk.CheckButton checkbutton2;
        
        private Gtk.SpinButton spinbutton2;
        
        private Gtk.Label label8;
        
        private Gtk.HBox hbox5;
        
        private Gtk.Label label9;
        
        private Gtk.Label label10;
        
        private Gtk.HScale hscale2;
        
        private Gtk.HBox hbox6;
        
        private Gtk.Label label11;
        
        private Gtk.ComboBox combobox5;
        
        private Gtk.HBox hbox7;
        
        private Gtk.Label label12;
        
        private Gtk.ComboBox combobox6;
        
        private Gtk.CheckButton checkbutton3;
        
        private Gtk.Label label7;
        
        private Gtk.HSeparator hseparator2;
        
        private Gtk.Frame frame1;
        
        private Gtk.Alignment GtkAlignment6;
        
        private Gtk.HBox hbox1;
        
        private Gtk.ComboBox combobox4;
        
        private Gtk.HButtonBox hbuttonbox2;
        
        private Gtk.Button button82;
        
        private Gtk.Button button83;
        
        private Gtk.Button button84;
        
        private Gtk.Label GtkLabel13;
        
        private Gtk.Button buttonOk;
        
        protected virtual void Build() {
            Stetic.Gui.Initialize(this);
            // Widget DeMixer.ConfigDlg
            this.Name = "DeMixer.ConfigDlg";
            this.WindowPosition = ((Gtk.WindowPosition)(1));
            this.Modal = true;
            this.BorderWidth = ((uint)(6));
            this.HasSeparator = false;
            // Internal child DeMixer.ConfigDlg.VBox
            Gtk.VBox w1 = this.VBox;
            w1.Name = "dialog1_VBox";
            w1.BorderWidth = ((uint)(2));
            // Container child dialog1_VBox.Gtk.Box+BoxChild
            this.vbox2 = new Gtk.VBox();
            this.vbox2.Name = "vbox2";
            this.vbox2.Spacing = 6;
            // Container child vbox2.Gtk.Box+BoxChild
            this.notebook1 = new Gtk.Notebook();
            this.notebook1.CanFocus = true;
            this.notebook1.Name = "notebook1";
            this.notebook1.CurrentPage = 0;
            // Container child notebook1.Gtk.Notebook+NotebookChild
            this.SourceVBox = new Gtk.VBox();
            this.SourceVBox.Name = "SourceVBox";
            this.SourceVBox.Spacing = 6;
            this.SourceVBox.BorderWidth = ((uint)(3));
            // Container child SourceVBox.Gtk.Box+BoxChild
            this.hbox8 = new Gtk.HBox();
            this.hbox8.Name = "hbox8";
            this.hbox8.Spacing = 6;
            // Container child hbox8.Gtk.Box+BoxChild
            this.vbox3 = new Gtk.VBox();
            this.vbox3.Name = "vbox3";
            this.vbox3.Spacing = 6;
            // Container child vbox3.Gtk.Box+BoxChild
            this.SourceComboBox = Gtk.ComboBox.NewText();
            this.SourceComboBox.CanFocus = true;
            this.SourceComboBox.Name = "SourceComboBox";
            this.vbox3.Add(this.SourceComboBox);
            Gtk.Box.BoxChild w2 = ((Gtk.Box.BoxChild)(this.vbox3[this.SourceComboBox]));
            w2.Position = 0;
            w2.Expand = false;
            w2.Fill = false;
            this.hbox8.Add(this.vbox3);
            Gtk.Box.BoxChild w3 = ((Gtk.Box.BoxChild)(this.hbox8[this.vbox3]));
            w3.Position = 0;
            w3.Expand = false;
            w3.Fill = false;
            // Container child hbox8.Gtk.Box+BoxChild
            this.SourceInformationLabel = new Gtk.Label();
            this.SourceInformationLabel.Name = "SourceInformationLabel";
            this.SourceInformationLabel.LabelProp = Mono.Unix.Catalog.GetString("SourceInformationLabel");
            this.SourceInformationLabel.UseMarkup = true;
            this.SourceInformationLabel.Wrap = true;
            this.SourceInformationLabel.Selectable = true;
            this.hbox8.Add(this.SourceInformationLabel);
            Gtk.Box.BoxChild w4 = ((Gtk.Box.BoxChild)(this.hbox8[this.SourceInformationLabel]));
            w4.Position = 1;
            this.SourceVBox.Add(this.hbox8);
            Gtk.Box.BoxChild w5 = ((Gtk.Box.BoxChild)(this.SourceVBox[this.hbox8]));
            w5.Position = 0;
            w5.Expand = false;
            w5.Fill = false;
            this.notebook1.Add(this.SourceVBox);
            // Notebook tab
            this.label1 = new Gtk.Label();
            this.label1.Name = "label1";
            this.label1.LabelProp = Mono.Unix.Catalog.GetString("Source");
            this.notebook1.SetTabLabel(this.SourceVBox, this.label1);
            this.label1.ShowAll();
            // Container child notebook1.Gtk.Notebook+NotebookChild
            this.CompositionVBox = new Gtk.VBox();
            this.CompositionVBox.Name = "CompositionVBox";
            this.CompositionVBox.Spacing = 6;
            this.CompositionVBox.BorderWidth = ((uint)(3));
            // Container child CompositionVBox.Gtk.Box+BoxChild
            this.hbox9 = new Gtk.HBox();
            this.hbox9.Name = "hbox9";
            this.hbox9.Spacing = 6;
            // Container child hbox9.Gtk.Box+BoxChild
            this.vbox4 = new Gtk.VBox();
            this.vbox4.Name = "vbox4";
            this.vbox4.Spacing = 6;
            // Container child vbox4.Gtk.Box+BoxChild
            this.CompositionComboBox = Gtk.ComboBox.NewText();
            this.CompositionComboBox.Name = "CompositionComboBox";
            this.vbox4.Add(this.CompositionComboBox);
            Gtk.Box.BoxChild w7 = ((Gtk.Box.BoxChild)(this.vbox4[this.CompositionComboBox]));
            w7.Position = 0;
            w7.Expand = false;
            w7.Fill = false;
            this.hbox9.Add(this.vbox4);
            Gtk.Box.BoxChild w8 = ((Gtk.Box.BoxChild)(this.hbox9[this.vbox4]));
            w8.Position = 0;
            w8.Expand = false;
            w8.Fill = false;
            // Container child hbox9.Gtk.Box+BoxChild
            this.CompositionInformationLabel = new Gtk.Label();
            this.CompositionInformationLabel.Name = "CompositionInformationLabel";
            this.CompositionInformationLabel.LabelProp = Mono.Unix.Catalog.GetString("CompositionInformationLabel");
            this.CompositionInformationLabel.UseMarkup = true;
            this.CompositionInformationLabel.Wrap = true;
            this.CompositionInformationLabel.Selectable = true;
            this.hbox9.Add(this.CompositionInformationLabel);
            Gtk.Box.BoxChild w9 = ((Gtk.Box.BoxChild)(this.hbox9[this.CompositionInformationLabel]));
            w9.Position = 1;
            this.CompositionVBox.Add(this.hbox9);
            Gtk.Box.BoxChild w10 = ((Gtk.Box.BoxChild)(this.CompositionVBox[this.hbox9]));
            w10.Position = 0;
            w10.Expand = false;
            w10.Fill = false;
            this.notebook1.Add(this.CompositionVBox);
            Gtk.Notebook.NotebookChild w11 = ((Gtk.Notebook.NotebookChild)(this.notebook1[this.CompositionVBox]));
            w11.Position = 1;
            // Notebook tab
            this.label3 = new Gtk.Label();
            this.label3.Name = "label3";
            this.label3.LabelProp = Mono.Unix.Catalog.GetString("Composition");
            this.notebook1.SetTabLabel(this.CompositionVBox, this.label3);
            this.label3.ShowAll();
            // Container child notebook1.Gtk.Notebook+NotebookChild
            this.vbox5 = new Gtk.VBox();
            this.vbox5.Name = "vbox5";
            this.vbox5.Spacing = 6;
            this.vbox5.BorderWidth = ((uint)(3));
            // Container child vbox5.Gtk.Box+BoxChild
            this.hbox2 = new Gtk.HBox();
            this.hbox2.Name = "hbox2";
            this.hbox2.Spacing = 6;
            // Container child hbox2.Gtk.Box+BoxChild
            this.vbox7 = new Gtk.VBox();
            this.vbox7.Name = "vbox7";
            this.vbox7.Spacing = 6;
            // Container child vbox7.Gtk.Box+BoxChild
            this.hbox10 = new Gtk.HBox();
            this.hbox10.Name = "hbox10";
            this.hbox10.Spacing = 6;
            // Container child hbox10.Gtk.Box+BoxChild
            this.EffectsComboBox = Gtk.ComboBox.NewText();
            this.EffectsComboBox.Name = "EffectsComboBox";
            this.hbox10.Add(this.EffectsComboBox);
            Gtk.Box.BoxChild w12 = ((Gtk.Box.BoxChild)(this.hbox10[this.EffectsComboBox]));
            w12.Position = 0;
            w12.Expand = false;
            w12.Fill = false;
            // Container child hbox10.Gtk.Box+BoxChild
            this.button37 = new Gtk.Button();
            this.button37.CanFocus = true;
            this.button37.Name = "button37";
            this.button37.UseUnderline = true;
            // Container child button37.Gtk.Container+ContainerChild
            Gtk.Alignment w13 = new Gtk.Alignment(0.5F, 0.5F, 0F, 0F);
            // Container child GtkAlignment.Gtk.Container+ContainerChild
            Gtk.HBox w14 = new Gtk.HBox();
            w14.Spacing = 2;
            // Container child GtkHBox3.Gtk.Container+ContainerChild
            Gtk.Image w15 = new Gtk.Image();
            w15.Pixbuf = Stetic.IconLoader.LoadIcon(this, "gtk-add", Gtk.IconSize.Menu, 19);
            w14.Add(w15);
            // Container child GtkHBox3.Gtk.Container+ContainerChild
            Gtk.Label w17 = new Gtk.Label();
            w17.LabelProp = Mono.Unix.Catalog.GetString("Add");
            w17.UseUnderline = true;
            w14.Add(w17);
            w13.Add(w14);
            this.button37.Add(w13);
            this.hbox10.Add(this.button37);
            Gtk.Box.BoxChild w21 = ((Gtk.Box.BoxChild)(this.hbox10[this.button37]));
            w21.Position = 1;
            w21.Expand = false;
            w21.Fill = false;
            this.vbox7.Add(this.hbox10);
            Gtk.Box.BoxChild w22 = ((Gtk.Box.BoxChild)(this.vbox7[this.hbox10]));
            w22.Position = 0;
            w22.Expand = false;
            w22.Fill = false;
            this.hbox2.Add(this.vbox7);
            Gtk.Box.BoxChild w23 = ((Gtk.Box.BoxChild)(this.hbox2[this.vbox7]));
            w23.Position = 0;
            w23.Expand = false;
            w23.Fill = false;
            // Container child hbox2.Gtk.Box+BoxChild
            this.EffectInformationLabel = new Gtk.Label();
            this.EffectInformationLabel.Name = "EffectInformationLabel";
            this.EffectInformationLabel.LabelProp = Mono.Unix.Catalog.GetString("EffectInformationLabel");
            this.EffectInformationLabel.UseMarkup = true;
            this.EffectInformationLabel.Wrap = true;
            this.EffectInformationLabel.Selectable = true;
            this.hbox2.Add(this.EffectInformationLabel);
            Gtk.Box.BoxChild w24 = ((Gtk.Box.BoxChild)(this.hbox2[this.EffectInformationLabel]));
            w24.Position = 1;
            this.vbox5.Add(this.hbox2);
            Gtk.Box.BoxChild w25 = ((Gtk.Box.BoxChild)(this.vbox5[this.hbox2]));
            w25.Position = 0;
            w25.Expand = false;
            w25.Fill = false;
            // Container child vbox5.Gtk.Box+BoxChild
            this.hbox3 = new Gtk.HBox();
            this.hbox3.Name = "hbox3";
            this.hbox3.Spacing = 6;
            // Container child hbox3.Gtk.Box+BoxChild
            this.iconview1 = new Gtk.IconView();
            this.iconview1.CanFocus = true;
            this.iconview1.Name = "iconview1";
            this.hbox3.Add(this.iconview1);
            Gtk.Box.BoxChild w26 = ((Gtk.Box.BoxChild)(this.hbox3[this.iconview1]));
            w26.Position = 0;
            // Container child hbox3.Gtk.Box+BoxChild
            this.vbuttonbox1 = new Gtk.VButtonBox();
            this.vbuttonbox1.Name = "vbuttonbox1";
            this.vbuttonbox1.Spacing = 4;
            this.vbuttonbox1.LayoutStyle = ((Gtk.ButtonBoxStyle)(3));
            // Container child vbuttonbox1.Gtk.ButtonBox+ButtonBoxChild
            this.button38 = new Gtk.Button();
            this.button38.CanFocus = true;
            this.button38.Name = "button38";
            this.button38.UseUnderline = true;
            // Container child button38.Gtk.Container+ContainerChild
            Gtk.Alignment w27 = new Gtk.Alignment(0.5F, 0.5F, 0F, 0F);
            // Container child GtkAlignment1.Gtk.Container+ContainerChild
            Gtk.HBox w28 = new Gtk.HBox();
            w28.Spacing = 2;
            // Container child GtkHBox4.Gtk.Container+ContainerChild
            Gtk.Image w29 = new Gtk.Image();
            w29.Pixbuf = Stetic.IconLoader.LoadIcon(this, "gtk-edit", Gtk.IconSize.Menu, 19);
            w28.Add(w29);
            // Container child GtkHBox4.Gtk.Container+ContainerChild
            Gtk.Label w31 = new Gtk.Label();
            w31.LabelProp = Mono.Unix.Catalog.GetString("_Edit");
            w31.UseUnderline = true;
            w28.Add(w31);
            w27.Add(w28);
            this.button38.Add(w27);
            this.vbuttonbox1.Add(this.button38);
            Gtk.ButtonBox.ButtonBoxChild w35 = ((Gtk.ButtonBox.ButtonBoxChild)(this.vbuttonbox1[this.button38]));
            w35.Expand = false;
            w35.Fill = false;
            // Container child vbuttonbox1.Gtk.ButtonBox+ButtonBoxChild
            this.button39 = new Gtk.Button();
            this.button39.CanFocus = true;
            this.button39.Name = "button39";
            this.button39.UseUnderline = true;
            // Container child button39.Gtk.Container+ContainerChild
            Gtk.Alignment w36 = new Gtk.Alignment(0.5F, 0.5F, 0F, 0F);
            // Container child GtkAlignment2.Gtk.Container+ContainerChild
            Gtk.HBox w37 = new Gtk.HBox();
            w37.Spacing = 2;
            // Container child GtkHBox5.Gtk.Container+ContainerChild
            Gtk.Image w38 = new Gtk.Image();
            w38.Pixbuf = Stetic.IconLoader.LoadIcon(this, "gtk-go-up", Gtk.IconSize.Menu, 19);
            w37.Add(w38);
            // Container child GtkHBox5.Gtk.Container+ContainerChild
            Gtk.Label w40 = new Gtk.Label();
            w40.LabelProp = Mono.Unix.Catalog.GetString("_Up");
            w40.UseUnderline = true;
            w37.Add(w40);
            w36.Add(w37);
            this.button39.Add(w36);
            this.vbuttonbox1.Add(this.button39);
            Gtk.ButtonBox.ButtonBoxChild w44 = ((Gtk.ButtonBox.ButtonBoxChild)(this.vbuttonbox1[this.button39]));
            w44.Position = 1;
            w44.Expand = false;
            w44.Fill = false;
            // Container child vbuttonbox1.Gtk.ButtonBox+ButtonBoxChild
            this.button40 = new Gtk.Button();
            this.button40.CanFocus = true;
            this.button40.Name = "button40";
            this.button40.UseUnderline = true;
            // Container child button40.Gtk.Container+ContainerChild
            Gtk.Alignment w45 = new Gtk.Alignment(0.5F, 0.5F, 0F, 0F);
            // Container child GtkAlignment3.Gtk.Container+ContainerChild
            Gtk.HBox w46 = new Gtk.HBox();
            w46.Spacing = 2;
            // Container child GtkHBox6.Gtk.Container+ContainerChild
            Gtk.Image w47 = new Gtk.Image();
            w47.Pixbuf = Stetic.IconLoader.LoadIcon(this, "gtk-go-down", Gtk.IconSize.Menu, 19);
            w46.Add(w47);
            // Container child GtkHBox6.Gtk.Container+ContainerChild
            Gtk.Label w49 = new Gtk.Label();
            w49.LabelProp = Mono.Unix.Catalog.GetString("Do_wn");
            w49.UseUnderline = true;
            w46.Add(w49);
            w45.Add(w46);
            this.button40.Add(w45);
            this.vbuttonbox1.Add(this.button40);
            Gtk.ButtonBox.ButtonBoxChild w53 = ((Gtk.ButtonBox.ButtonBoxChild)(this.vbuttonbox1[this.button40]));
            w53.Position = 2;
            w53.Expand = false;
            w53.Fill = false;
            // Container child vbuttonbox1.Gtk.ButtonBox+ButtonBoxChild
            this.button41 = new Gtk.Button();
            this.button41.CanFocus = true;
            this.button41.Name = "button41";
            this.button41.UseUnderline = true;
            // Container child button41.Gtk.Container+ContainerChild
            Gtk.Alignment w54 = new Gtk.Alignment(0.5F, 0.5F, 0F, 0F);
            // Container child GtkAlignment4.Gtk.Container+ContainerChild
            Gtk.HBox w55 = new Gtk.HBox();
            w55.Spacing = 2;
            // Container child GtkHBox7.Gtk.Container+ContainerChild
            Gtk.Image w56 = new Gtk.Image();
            w56.Pixbuf = Stetic.IconLoader.LoadIcon(this, "gtk-copy", Gtk.IconSize.Menu, 19);
            w55.Add(w56);
            // Container child GtkHBox7.Gtk.Container+ContainerChild
            Gtk.Label w58 = new Gtk.Label();
            w58.LabelProp = Mono.Unix.Catalog.GetString("_Clone");
            w58.UseUnderline = true;
            w55.Add(w58);
            w54.Add(w55);
            this.button41.Add(w54);
            this.vbuttonbox1.Add(this.button41);
            Gtk.ButtonBox.ButtonBoxChild w62 = ((Gtk.ButtonBox.ButtonBoxChild)(this.vbuttonbox1[this.button41]));
            w62.Position = 3;
            w62.Expand = false;
            w62.Fill = false;
            // Container child vbuttonbox1.Gtk.ButtonBox+ButtonBoxChild
            this.button42 = new Gtk.Button();
            this.button42.CanFocus = true;
            this.button42.Name = "button42";
            this.button42.UseUnderline = true;
            // Container child button42.Gtk.Container+ContainerChild
            Gtk.Alignment w63 = new Gtk.Alignment(0.5F, 0.5F, 0F, 0F);
            // Container child GtkAlignment5.Gtk.Container+ContainerChild
            Gtk.HBox w64 = new Gtk.HBox();
            w64.Spacing = 2;
            // Container child GtkHBox8.Gtk.Container+ContainerChild
            Gtk.Image w65 = new Gtk.Image();
            w65.Pixbuf = Stetic.IconLoader.LoadIcon(this, "gtk-delete", Gtk.IconSize.Menu, 19);
            w64.Add(w65);
            // Container child GtkHBox8.Gtk.Container+ContainerChild
            Gtk.Label w67 = new Gtk.Label();
            w67.LabelProp = Mono.Unix.Catalog.GetString("_Delete");
            w67.UseUnderline = true;
            w64.Add(w67);
            w63.Add(w64);
            this.button42.Add(w63);
            this.vbuttonbox1.Add(this.button42);
            Gtk.ButtonBox.ButtonBoxChild w71 = ((Gtk.ButtonBox.ButtonBoxChild)(this.vbuttonbox1[this.button42]));
            w71.Position = 4;
            w71.Expand = false;
            w71.Fill = false;
            this.hbox3.Add(this.vbuttonbox1);
            Gtk.Box.BoxChild w72 = ((Gtk.Box.BoxChild)(this.hbox3[this.vbuttonbox1]));
            w72.Position = 1;
            w72.Expand = false;
            w72.Fill = false;
            this.vbox5.Add(this.hbox3);
            Gtk.Box.BoxChild w73 = ((Gtk.Box.BoxChild)(this.vbox5[this.hbox3]));
            w73.Position = 1;
            this.notebook1.Add(this.vbox5);
            Gtk.Notebook.NotebookChild w74 = ((Gtk.Notebook.NotebookChild)(this.notebook1[this.vbox5]));
            w74.Position = 2;
            // Notebook tab
            this.label5 = new Gtk.Label();
            this.label5.Name = "label5";
            this.label5.LabelProp = Mono.Unix.Catalog.GetString("Effects");
            this.notebook1.SetTabLabel(this.vbox5, this.label5);
            this.label5.ShowAll();
            // Container child notebook1.Gtk.Notebook+NotebookChild
            this.vbox6 = new Gtk.VBox();
            this.vbox6.Name = "vbox6";
            this.vbox6.Spacing = 6;
            this.vbox6.BorderWidth = ((uint)(3));
            // Container child vbox6.Gtk.Box+BoxChild
            this.hbox4 = new Gtk.HBox();
            this.hbox4.Name = "hbox4";
            this.hbox4.Spacing = 6;
            // Container child hbox4.Gtk.Box+BoxChild
            this.checkbutton1 = new Gtk.CheckButton();
            this.checkbutton1.CanFocus = true;
            this.checkbutton1.Name = "checkbutton1";
            this.checkbutton1.Label = Mono.Unix.Catalog.GetString("Save history");
            this.checkbutton1.DrawIndicator = true;
            this.checkbutton1.UseUnderline = true;
            this.hbox4.Add(this.checkbutton1);
            Gtk.Box.BoxChild w75 = ((Gtk.Box.BoxChild)(this.hbox4[this.checkbutton1]));
            w75.Position = 0;
            w75.Expand = false;
            w75.Fill = false;
            // Container child hbox4.Gtk.Box+BoxChild
            this.filechooserbutton1 = new Gtk.FileChooserButton(Mono.Unix.Catalog.GetString("Выберите файл"), ((Gtk.FileChooserAction)(2)));
            this.filechooserbutton1.Name = "filechooserbutton1";
            this.filechooserbutton1.ShowHidden = true;
            this.hbox4.Add(this.filechooserbutton1);
            Gtk.Box.BoxChild w76 = ((Gtk.Box.BoxChild)(this.hbox4[this.filechooserbutton1]));
            w76.Position = 1;
            // Container child hbox4.Gtk.Box+BoxChild
            this.checkbutton2 = new Gtk.CheckButton();
            this.checkbutton2.CanFocus = true;
            this.checkbutton2.Name = "checkbutton2";
            this.checkbutton2.Label = Mono.Unix.Catalog.GetString("Max size");
            this.checkbutton2.DrawIndicator = true;
            this.checkbutton2.UseUnderline = true;
            this.hbox4.Add(this.checkbutton2);
            Gtk.Box.BoxChild w77 = ((Gtk.Box.BoxChild)(this.hbox4[this.checkbutton2]));
            w77.Position = 2;
            w77.Expand = false;
            w77.Fill = false;
            // Container child hbox4.Gtk.Box+BoxChild
            this.spinbutton2 = new Gtk.SpinButton(0, 100, 1);
            this.spinbutton2.CanFocus = true;
            this.spinbutton2.Name = "spinbutton2";
            this.spinbutton2.Adjustment.PageIncrement = 10;
            this.spinbutton2.ClimbRate = 1;
            this.spinbutton2.Numeric = true;
            this.hbox4.Add(this.spinbutton2);
            Gtk.Box.BoxChild w78 = ((Gtk.Box.BoxChild)(this.hbox4[this.spinbutton2]));
            w78.Position = 3;
            w78.Expand = false;
            w78.Fill = false;
            // Container child hbox4.Gtk.Box+BoxChild
            this.label8 = new Gtk.Label();
            this.label8.Name = "label8";
            this.label8.LabelProp = Mono.Unix.Catalog.GetString("Mb");
            this.hbox4.Add(this.label8);
            Gtk.Box.BoxChild w79 = ((Gtk.Box.BoxChild)(this.hbox4[this.label8]));
            w79.Position = 4;
            w79.Expand = false;
            w79.Fill = false;
            this.vbox6.Add(this.hbox4);
            Gtk.Box.BoxChild w80 = ((Gtk.Box.BoxChild)(this.vbox6[this.hbox4]));
            w80.Position = 0;
            w80.Expand = false;
            w80.Fill = false;
            // Container child vbox6.Gtk.Box+BoxChild
            this.hbox5 = new Gtk.HBox();
            this.hbox5.Name = "hbox5";
            this.hbox5.Spacing = 6;
            // Container child hbox5.Gtk.Box+BoxChild
            this.label9 = new Gtk.Label();
            this.label9.Name = "label9";
            this.label9.LabelProp = Mono.Unix.Catalog.GetString("Update interval:");
            this.hbox5.Add(this.label9);
            Gtk.Box.BoxChild w81 = ((Gtk.Box.BoxChild)(this.hbox5[this.label9]));
            w81.Position = 0;
            w81.Expand = false;
            w81.Fill = false;
            // Container child hbox5.Gtk.Box+BoxChild
            this.label10 = new Gtk.Label();
            this.label10.Name = "label10";
            this.label10.LabelProp = Mono.Unix.Catalog.GetString("1 min");
            this.hbox5.Add(this.label10);
            Gtk.Box.BoxChild w82 = ((Gtk.Box.BoxChild)(this.hbox5[this.label10]));
            w82.Position = 1;
            w82.Expand = false;
            w82.Fill = false;
            // Container child hbox5.Gtk.Box+BoxChild
            this.hscale2 = new Gtk.HScale(null);
            this.hscale2.CanFocus = true;
            this.hscale2.Name = "hscale2";
            this.hscale2.Adjustment.Upper = 100;
            this.hscale2.Adjustment.PageIncrement = 10;
            this.hscale2.Adjustment.StepIncrement = 1;
            this.hscale2.DrawValue = false;
            this.hscale2.Digits = 0;
            this.hscale2.ValuePos = ((Gtk.PositionType)(2));
            this.hbox5.Add(this.hscale2);
            Gtk.Box.BoxChild w83 = ((Gtk.Box.BoxChild)(this.hbox5[this.hscale2]));
            w83.Position = 2;
            this.vbox6.Add(this.hbox5);
            Gtk.Box.BoxChild w84 = ((Gtk.Box.BoxChild)(this.vbox6[this.hbox5]));
            w84.Position = 1;
            w84.Expand = false;
            w84.Fill = false;
            // Container child vbox6.Gtk.Box+BoxChild
            this.hbox6 = new Gtk.HBox();
            this.hbox6.Name = "hbox6";
            this.hbox6.Spacing = 6;
            // Container child hbox6.Gtk.Box+BoxChild
            this.label11 = new Gtk.Label();
            this.label11.Name = "label11";
            this.label11.LabelProp = Mono.Unix.Catalog.GetString("Update Mode");
            this.hbox6.Add(this.label11);
            Gtk.Box.BoxChild w85 = ((Gtk.Box.BoxChild)(this.hbox6[this.label11]));
            w85.Position = 0;
            w85.Expand = false;
            w85.Fill = false;
            // Container child hbox6.Gtk.Box+BoxChild
            this.combobox5 = Gtk.ComboBox.NewText();
            this.combobox5.AppendText(Mono.Unix.Catalog.GetString("Updata on start"));
            this.combobox5.AppendText(Mono.Unix.Catalog.GetString("Wait after start"));
            this.combobox5.AppendText(Mono.Unix.Catalog.GetString("Wait from last update"));
            this.combobox5.Name = "combobox5";
            this.combobox5.Active = 1;
            this.hbox6.Add(this.combobox5);
            Gtk.Box.BoxChild w86 = ((Gtk.Box.BoxChild)(this.hbox6[this.combobox5]));
            w86.Position = 1;
            this.vbox6.Add(this.hbox6);
            Gtk.Box.BoxChild w87 = ((Gtk.Box.BoxChild)(this.vbox6[this.hbox6]));
            w87.Position = 2;
            w87.Expand = false;
            w87.Fill = false;
            // Container child vbox6.Gtk.Box+BoxChild
            this.hbox7 = new Gtk.HBox();
            this.hbox7.Name = "hbox7";
            this.hbox7.Spacing = 6;
            // Container child hbox7.Gtk.Box+BoxChild
            this.label12 = new Gtk.Label();
            this.label12.Name = "label12";
            this.label12.LabelProp = Mono.Unix.Catalog.GetString("Language");
            this.hbox7.Add(this.label12);
            Gtk.Box.BoxChild w88 = ((Gtk.Box.BoxChild)(this.hbox7[this.label12]));
            w88.Position = 0;
            w88.Expand = false;
            w88.Fill = false;
            // Container child hbox7.Gtk.Box+BoxChild
            this.combobox6 = Gtk.ComboBox.NewText();
            this.combobox6.Name = "combobox6";
            this.hbox7.Add(this.combobox6);
            Gtk.Box.BoxChild w89 = ((Gtk.Box.BoxChild)(this.hbox7[this.combobox6]));
            w89.Position = 1;
            this.vbox6.Add(this.hbox7);
            Gtk.Box.BoxChild w90 = ((Gtk.Box.BoxChild)(this.vbox6[this.hbox7]));
            w90.Position = 3;
            w90.Expand = false;
            w90.Fill = false;
            // Container child vbox6.Gtk.Box+BoxChild
            this.checkbutton3 = new Gtk.CheckButton();
            this.checkbutton3.CanFocus = true;
            this.checkbutton3.Name = "checkbutton3";
            this.checkbutton3.Label = Mono.Unix.Catalog.GetString("Autorun");
            this.checkbutton3.DrawIndicator = true;
            this.checkbutton3.UseUnderline = true;
            this.vbox6.Add(this.checkbutton3);
            Gtk.Box.BoxChild w91 = ((Gtk.Box.BoxChild)(this.vbox6[this.checkbutton3]));
            w91.Position = 4;
            w91.Expand = false;
            w91.Fill = false;
            this.notebook1.Add(this.vbox6);
            Gtk.Notebook.NotebookChild w92 = ((Gtk.Notebook.NotebookChild)(this.notebook1[this.vbox6]));
            w92.Position = 3;
            // Notebook tab
            this.label7 = new Gtk.Label();
            this.label7.Name = "label7";
            this.label7.LabelProp = Mono.Unix.Catalog.GetString("Program");
            this.notebook1.SetTabLabel(this.vbox6, this.label7);
            this.label7.ShowAll();
            this.vbox2.Add(this.notebook1);
            Gtk.Box.BoxChild w93 = ((Gtk.Box.BoxChild)(this.vbox2[this.notebook1]));
            w93.Position = 0;
            // Container child vbox2.Gtk.Box+BoxChild
            this.hseparator2 = new Gtk.HSeparator();
            this.hseparator2.Name = "hseparator2";
            this.vbox2.Add(this.hseparator2);
            Gtk.Box.BoxChild w94 = ((Gtk.Box.BoxChild)(this.vbox2[this.hseparator2]));
            w94.Position = 1;
            w94.Expand = false;
            w94.Fill = false;
            // Container child vbox2.Gtk.Box+BoxChild
            this.frame1 = new Gtk.Frame();
            this.frame1.Name = "frame1";
            this.frame1.ShadowType = ((Gtk.ShadowType)(0));
            // Container child frame1.Gtk.Container+ContainerChild
            this.GtkAlignment6 = new Gtk.Alignment(0F, 0F, 1F, 1F);
            this.GtkAlignment6.Name = "GtkAlignment6";
            this.GtkAlignment6.LeftPadding = ((uint)(12));
            // Container child GtkAlignment6.Gtk.Container+ContainerChild
            this.hbox1 = new Gtk.HBox();
            this.hbox1.Name = "hbox1";
            this.hbox1.Spacing = 6;
            // Container child hbox1.Gtk.Box+BoxChild
            this.combobox4 = Gtk.ComboBox.NewText();
            this.combobox4.Name = "combobox4";
            this.hbox1.Add(this.combobox4);
            Gtk.Box.BoxChild w95 = ((Gtk.Box.BoxChild)(this.hbox1[this.combobox4]));
            w95.Position = 0;
            // Container child hbox1.Gtk.Box+BoxChild
            this.hbuttonbox2 = new Gtk.HButtonBox();
            this.hbuttonbox2.Name = "hbuttonbox2";
            this.hbuttonbox2.Spacing = 4;
            this.hbuttonbox2.LayoutStyle = ((Gtk.ButtonBoxStyle)(4));
            // Container child hbuttonbox2.Gtk.ButtonBox+ButtonBoxChild
            this.button82 = new Gtk.Button();
            this.button82.CanFocus = true;
            this.button82.Name = "button82";
            this.button82.UseUnderline = true;
            // Container child button82.Gtk.Container+ContainerChild
            Gtk.Alignment w96 = new Gtk.Alignment(0.5F, 0.5F, 0F, 0F);
            // Container child GtkAlignment7.Gtk.Container+ContainerChild
            Gtk.HBox w97 = new Gtk.HBox();
            w97.Spacing = 2;
            // Container child GtkHBox14.Gtk.Container+ContainerChild
            Gtk.Image w98 = new Gtk.Image();
            w98.Pixbuf = Stetic.IconLoader.LoadIcon(this, "gtk-apply", Gtk.IconSize.Menu, 19);
            w97.Add(w98);
            // Container child GtkHBox14.Gtk.Container+ContainerChild
            Gtk.Label w100 = new Gtk.Label();
            w100.LabelProp = Mono.Unix.Catalog.GetString("_Apply");
            w100.UseUnderline = true;
            w97.Add(w100);
            w96.Add(w97);
            this.button82.Add(w96);
            this.hbuttonbox2.Add(this.button82);
            Gtk.ButtonBox.ButtonBoxChild w104 = ((Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox2[this.button82]));
            w104.Expand = false;
            w104.Fill = false;
            // Container child hbuttonbox2.Gtk.ButtonBox+ButtonBoxChild
            this.button83 = new Gtk.Button();
            this.button83.CanFocus = true;
            this.button83.Name = "button83";
            this.button83.UseUnderline = true;
            // Container child button83.Gtk.Container+ContainerChild
            Gtk.Alignment w105 = new Gtk.Alignment(0.5F, 0.5F, 0F, 0F);
            // Container child GtkAlignment8.Gtk.Container+ContainerChild
            Gtk.HBox w106 = new Gtk.HBox();
            w106.Spacing = 2;
            // Container child GtkHBox15.Gtk.Container+ContainerChild
            Gtk.Image w107 = new Gtk.Image();
            w107.Pixbuf = Stetic.IconLoader.LoadIcon(this, "gtk-save", Gtk.IconSize.Menu, 19);
            w106.Add(w107);
            // Container child GtkHBox15.Gtk.Container+ContainerChild
            Gtk.Label w109 = new Gtk.Label();
            w109.LabelProp = Mono.Unix.Catalog.GetString("_Save");
            w109.UseUnderline = true;
            w106.Add(w109);
            w105.Add(w106);
            this.button83.Add(w105);
            this.hbuttonbox2.Add(this.button83);
            Gtk.ButtonBox.ButtonBoxChild w113 = ((Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox2[this.button83]));
            w113.Position = 1;
            w113.Expand = false;
            w113.Fill = false;
            // Container child hbuttonbox2.Gtk.ButtonBox+ButtonBoxChild
            this.button84 = new Gtk.Button();
            this.button84.CanFocus = true;
            this.button84.Name = "button84";
            this.button84.UseUnderline = true;
            // Container child button84.Gtk.Container+ContainerChild
            Gtk.Alignment w114 = new Gtk.Alignment(0.5F, 0.5F, 0F, 0F);
            // Container child GtkAlignment9.Gtk.Container+ContainerChild
            Gtk.HBox w115 = new Gtk.HBox();
            w115.Spacing = 2;
            // Container child GtkHBox16.Gtk.Container+ContainerChild
            Gtk.Image w116 = new Gtk.Image();
            w116.Pixbuf = Stetic.IconLoader.LoadIcon(this, "gtk-delete", Gtk.IconSize.Menu, 19);
            w115.Add(w116);
            // Container child GtkHBox16.Gtk.Container+ContainerChild
            Gtk.Label w118 = new Gtk.Label();
            w118.LabelProp = Mono.Unix.Catalog.GetString("_Delete");
            w118.UseUnderline = true;
            w115.Add(w118);
            w114.Add(w115);
            this.button84.Add(w114);
            this.hbuttonbox2.Add(this.button84);
            Gtk.ButtonBox.ButtonBoxChild w122 = ((Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox2[this.button84]));
            w122.Position = 2;
            w122.Expand = false;
            w122.Fill = false;
            this.hbox1.Add(this.hbuttonbox2);
            Gtk.Box.BoxChild w123 = ((Gtk.Box.BoxChild)(this.hbox1[this.hbuttonbox2]));
            w123.Position = 1;
            w123.Expand = false;
            w123.Fill = false;
            this.GtkAlignment6.Add(this.hbox1);
            this.frame1.Add(this.GtkAlignment6);
            this.GtkLabel13 = new Gtk.Label();
            this.GtkLabel13.Name = "GtkLabel13";
            this.GtkLabel13.LabelProp = Mono.Unix.Catalog.GetString("<b>Profiles</b>");
            this.GtkLabel13.UseMarkup = true;
            this.frame1.LabelWidget = this.GtkLabel13;
            this.vbox2.Add(this.frame1);
            Gtk.Box.BoxChild w126 = ((Gtk.Box.BoxChild)(this.vbox2[this.frame1]));
            w126.Position = 2;
            w126.Expand = false;
            w126.Fill = false;
            w1.Add(this.vbox2);
            Gtk.Box.BoxChild w127 = ((Gtk.Box.BoxChild)(w1[this.vbox2]));
            w127.Position = 0;
            // Internal child DeMixer.ConfigDlg.ActionArea
            Gtk.HButtonBox w128 = this.ActionArea;
            w128.Name = "dialog1_ActionArea";
            w128.Spacing = 6;
            w128.BorderWidth = ((uint)(5));
            w128.LayoutStyle = ((Gtk.ButtonBoxStyle)(4));
            // Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
            this.buttonOk = new Gtk.Button();
            this.buttonOk.CanDefault = true;
            this.buttonOk.CanFocus = true;
            this.buttonOk.Name = "buttonOk";
            this.buttonOk.UseUnderline = true;
            // Container child buttonOk.Gtk.Container+ContainerChild
            Gtk.Alignment w129 = new Gtk.Alignment(0.5F, 0.5F, 0F, 0F);
            // Container child GtkAlignment10.Gtk.Container+ContainerChild
            Gtk.HBox w130 = new Gtk.HBox();
            w130.Spacing = 2;
            // Container child GtkHBox17.Gtk.Container+ContainerChild
            Gtk.Image w131 = new Gtk.Image();
            w131.Pixbuf = Stetic.IconLoader.LoadIcon(this, "gtk-close", Gtk.IconSize.Menu, 19);
            w130.Add(w131);
            // Container child GtkHBox17.Gtk.Container+ContainerChild
            Gtk.Label w133 = new Gtk.Label();
            w133.LabelProp = Mono.Unix.Catalog.GetString("_Close");
            w133.UseUnderline = true;
            w130.Add(w133);
            w129.Add(w130);
            this.buttonOk.Add(w129);
            this.AddActionWidget(this.buttonOk, -7);
            Gtk.ButtonBox.ButtonBoxChild w137 = ((Gtk.ButtonBox.ButtonBoxChild)(w128[this.buttonOk]));
            w137.Expand = false;
            w137.Fill = false;
            if ((this.Child != null)) {
                this.Child.ShowAll();
            }
            this.DefaultWidth = 506;
            this.DefaultHeight = 397;
            this.Show();
            this.SourceComboBox.Changed += new System.EventHandler(this.OnSourceComboBoxChanged);
            this.CompositionComboBox.Changed += new System.EventHandler(this.OnCompositionComboBoxChanged);
            this.EffectsComboBox.Changed += new System.EventHandler(this.OnEffectsComboBoxChanged);
            this.button83.Clicked += new System.EventHandler(this.OnButton83Clicked);
        }
    }
}
