
// This file has been generated by the GUI designer. Do not modify.
namespace DeMixer.lib.std
{
	public partial class FlickrSourceConfigView
	{
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget DeMixer.lib.std.FlickrSourceConfigView
			global::Stetic.BinContainer.Attach (this);
			this.Name = "DeMixer.lib.std.FlickrSourceConfigView";
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
		}
	}
}
