
// This file has been generated by the GUI designer. Do not modify.
namespace DeMixer.lib.std
{
	public partial class konachancomSourceConfigView
	{
		private global::Gtk.VBox vbox4;
		private global::Gtk.HBox hbox6;
		private global::Gtk.Label tagsLabel;
		private global::Gtk.Entry tagsEdit;
		
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget DeMixer.lib.std.konachancomSourceConfigView
			global::Stetic.BinContainer.Attach (this);
			this.Name = "DeMixer.lib.std.konachancomSourceConfigView";
			// Container child DeMixer.lib.std.konachancomSourceConfigView.Gtk.Container+ContainerChild
			this.vbox4 = new global::Gtk.VBox ();
			this.vbox4.Name = "vbox4";
			this.vbox4.Spacing = 6;
			// Container child vbox4.Gtk.Box+BoxChild
			this.hbox6 = new global::Gtk.HBox ();
			this.hbox6.Name = "hbox6";
			this.hbox6.Spacing = 6;
			// Container child hbox6.Gtk.Box+BoxChild
			this.tagsLabel = new global::Gtk.Label ();
			this.tagsLabel.Name = "tagsLabel";
			this.tagsLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("tags");
			this.hbox6.Add (this.tagsLabel);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox6 [this.tagsLabel]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child hbox6.Gtk.Box+BoxChild
			this.tagsEdit = new global::Gtk.Entry ();
			this.tagsEdit.CanFocus = true;
			this.tagsEdit.Name = "tagsEdit";
			this.tagsEdit.IsEditable = true;
			this.tagsEdit.InvisibleChar = '●';
			this.hbox6.Add (this.tagsEdit);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox6 [this.tagsEdit]));
			w2.Position = 1;
			this.vbox4.Add (this.hbox6);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.hbox6]));
			w3.Position = 0;
			w3.Expand = false;
			w3.Fill = false;
			this.Add (this.vbox4);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
			this.tagsEdit.Changed += new global::System.EventHandler (this.OnTagsEditChanged);
		}
	}
}
