// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace DeMixer.lib.std {
    
    
    public partial class konachancomSourceConfigView {
        
        private Gtk.VBox vbox4;
        
        private Gtk.HBox hbox6;
        
        private Gtk.Label tagsLabel;
        
        private Gtk.Entry tagsEdit;
        
        protected virtual void Build() {
            Stetic.Gui.Initialize(this);
            // Widget DeMixer.lib.std.konachancomSourceConfigView
            Stetic.BinContainer.Attach(this);
            this.Name = "DeMixer.lib.std.konachancomSourceConfigView";
            // Container child DeMixer.lib.std.konachancomSourceConfigView.Gtk.Container+ContainerChild
            this.vbox4 = new Gtk.VBox();
            this.vbox4.Name = "vbox4";
            this.vbox4.Spacing = 6;
            // Container child vbox4.Gtk.Box+BoxChild
            this.hbox6 = new Gtk.HBox();
            this.hbox6.Name = "hbox6";
            this.hbox6.Spacing = 6;
            // Container child hbox6.Gtk.Box+BoxChild
            this.tagsLabel = new Gtk.Label();
            this.tagsLabel.Name = "tagsLabel";
            this.tagsLabel.LabelProp = Mono.Unix.Catalog.GetString("tags");
            this.hbox6.Add(this.tagsLabel);
            Gtk.Box.BoxChild w1 = ((Gtk.Box.BoxChild)(this.hbox6[this.tagsLabel]));
            w1.Position = 0;
            w1.Expand = false;
            w1.Fill = false;
            // Container child hbox6.Gtk.Box+BoxChild
            this.tagsEdit = new Gtk.Entry();
            this.tagsEdit.CanFocus = true;
            this.tagsEdit.Name = "tagsEdit";
            this.tagsEdit.IsEditable = true;
            this.tagsEdit.InvisibleChar = '●';
            this.hbox6.Add(this.tagsEdit);
            Gtk.Box.BoxChild w2 = ((Gtk.Box.BoxChild)(this.hbox6[this.tagsEdit]));
            w2.Position = 1;
            this.vbox4.Add(this.hbox6);
            Gtk.Box.BoxChild w3 = ((Gtk.Box.BoxChild)(this.vbox4[this.hbox6]));
            w3.Position = 0;
            w3.Expand = false;
            w3.Fill = false;
            this.Add(this.vbox4);
            if ((this.Child != null)) {
                this.Child.ShowAll();
            }
            this.Hide();
            this.tagsEdit.Changed += new System.EventHandler(this.OnTagsEditChanged);
        }
    }
}
